### ISSUE TITLE
Cannot use v4.1.0 inside a yarn workspace

### ISSUE THREAD

**Issue by paulsouche** [dherges/ng-packagr#1051]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[ X ] Regression
```

## Description

Since v4.1.0 the `ngc` build fails with error

```
BUILD ERROR
: Error: Trying to import a source file from a node_modules package: ...
    at TsCompilerAotCompilerTypeCheckHostAdapter.fileNameToModuleName (path)
    at TsCompilerAotCompilerTypeCheckHostAdapter.toSummaryFileName (path)
    at AotSummaryResolver.toSummaryFileName (path)
    at packages/compiler/src/aot/summary_serializer.ts:204:42
    at Array.map (<anonymous>)
    at ToJsonSerializer.serialize (packages/compiler/src/aot/summary_serializer.ts:186:29)
    at serializeSummaries (packages/compiler/src/aot/summary_serializer.ts:39:9)
    at AotCompiler._createSummary (packages/compiler/src/aot/compiler.ts:554:11)
    at AotCompiler._compileImplFile (packages/compiler/src/aot/compiler.ts:475:17)
    at packages/compiler/src/aot/compiler.ts:459:22
```

Everything works fine with the 3.0.6 version

Basically [fileNameToModuleName](https://github.com/angular/angular/blob/master/packages/compiler-cli/src/transformers/compiler_host.ts#L194) fails when trying to resolve a workspace package.

#### How To Reproduce

You can use [our repository](https://github.com/santech-org/studio/tree/chore-migration). Be sure to upgrade ng-packagr version.

#### Expected Behaviour

No error

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 4.1.0
@angular/*: 6.1.3
typescript: 2.9.2
rxjs: latest
node: latest
npm/yarn: latest
```

I will try other 4.x versions in order to find the incriminated change

Thanks anyway for the great job !

**Comment by alan-agius4** [comment]
In `ng-packagr` version 4 we removed a lot of logic and are now using the Angular Compiler directly. 

My 2 cents would be that this issue is reproducible with `ngc` directly. I'll try to check when I have some time in the coming days.

**Comment by paulsouche** [comment]
Hi,

I totally agree with you ! I thought however there was an issue with our repository because `index.ts` files where at package root in some libraries. In consequence `ngc` resolution could raise errors. So I moved all our codebase in `src` folders. But that does not fix the issue 😠 ... Our repository is updated.

I debugged a little and saw that [importedFilePackageName](https://github.com/angular/angular/blob/c95437f15df93e2ca735ebf015acb20be597bb6a/packages/compiler-cli/src/transformers/compiler_host.ts#L214) was null because the [node_modules regex](https://github.com/angular/angular/blob/c95437f15df93e2ca735ebf015acb20be597bb6a/packages/compiler-cli/src/transformers/compiler_host.ts#L635) does not match the `filePath`. That's because the `filePath` refers to the package in the monorepo and not to the symbolic link in the `node_modules` of the workspace. I will inspect how this filePath is populated and see if there is not a problem with symbolic links.

BTW if I remove [this check](https://github.com/angular/angular/blob/c95437f15df93e2ca735ebf015acb20be597bb6a/packages/compiler-cli/src/transformers/compiler_host.ts#L228) all works like a charm so it's definitely an angular issue.

So should we open an issue to angular compiler ? Or could you find a way to provide a [context.fileNameToModuleName](https://github.com/angular/angular/blob/c95437f15df93e2ca735ebf015acb20be597bb6a/packages/compiler-cli/src/transformers/compiler_host.ts#L113) as it was done in `ng-packagr` v3 ?

Thanks again for the great job !

**Comment by alan-agius4** [comment]
I think it's best that the issue is address by Angular Compiler guys. Since it's an upstream issue. AFAIK in V3, we are not using `fileNameToModuleName` either.

**Comment by paulsouche** [comment]
Indeed !!! My mistake ! I confused the two methods `fileNameToModuleName` and `moduleNameToFileName`.

Anyway I found the problem inspecting how `filePath` was populated and I think we lose our two cents...

You can see [here](https://github.com/angular/angular/blob/master/packages/compiler-cli/src/transformers/compiler_host.ts#L170) that if compiler host context provide `moduleNameToFileName`, it will be called instead of `resolveModuleName`. And that's the case in `ng-packagr` [here](https://github.com/dherges/ng-packagr/blob/master/src/lib/ts/cache-compiler-host.ts#L64).

The problem is that output of these methods is different

```
moduleNameToFileName => ${cwd}/@package/lib/dist/index.d.ts
resolveModuleName => ${cwd}/node_modules/@package/lib/dist/index.d.ts
```

And the explaination is that `ts.resolveModuleName` is not called the same way. You can see [here](https://github.com/angular/angular/blob/master/packages/compiler-cli/src/transformers/compiler_host.ts#L135) that compiler-cli calls it with compiler host itself as fourth parameter. And in `ng-packagr` you call it with `compilerHost` that is equivalent to the context of the `TsCompilerAotCompilerTypeCheckHostAdapter`.

BTW `moduleNameToFileName` is not provided in v3.0.6 that's why I do not have the issue with it.

So there are 2 solutions

First we can tell angular please call it with `this.context` instead of `this` if context provide `moduleNameToFileName` but I'm pretty sure that they will not approve this change... However I did test it and it works.

Second is to remove (or change implementation of) `moduleNameToFileName` in [`cache-compiler-host.ts`](https://github.com/dherges/ng-packagr/blob/master/src/lib/ts/cache-compiler-host.ts). So I'm asking you if there is a reason to keep this? Again, I tested removing it and it works.

Please let me know (I can do a PR for sure 😄)

Thanks again

**Comment by alan-agius4** [comment]
The `moduleNameToFileName` implementation in the `cache-compiler-host.ts`. Is there so that for incremental builds it will use the `cachedModule` resolutions, as without it, the incremental builds will be slower.

**Comment by alan-agius4** [comment]
Maybe cashing  the compiler host would be an alternative. But we need to
see what implications it has are we’d need to catch multiple compiler host
rather than a single module cache.
