### ISSUE TITLE
'Module' is not exported by node_modules\primeng\primeng.js

### ISSUE THREAD

**Issue by HelySaul** [dherges/ng-packagr#142]
## Type of Issue

Problem exporting other components of primeng

- [ X] Bug Report
- [ ] Feature Request

## Description

I've been trying to creante a package with the packager. My app uses primeng but it says that the components of the library are not exported. The problem is with rollup:

 'InputSwitchModule' is not exported by node_modules\primeng\primeng.js
Error: 'InputSwitchModule' is not exported by node_modules\primeng\primeng.js
    at error (C:\Users\Hely\WebstormProjects\SysmarComponents\node_modules\rollup\dist\rollup.js:185:14)
    at Module.error (C:\Users\Hely\WebstormProjects\SysmarComponents\node_modules\rollup\dist\rollup.js:8390:3)
    at Module.trace (C:\Users\Hely\WebstormProjects\SysmarComponents\node_modules\rollup\dist\rollup.js:8487:10)
    at ModuleScope.findVariable (C:\Users\Hely\WebstormProjects\SysmarComponents\node_modules\rollup\dist\rollup.js:8093:22)
    at Node.bind (C:\Users\Hely\WebstormProjects\SysmarComponents\node_modules\rollup\dist\rollup.js:6996:31)
    at eachChild.child (C:\Users\Hely\WebstormProjects\SysmarComponents\node_modules\rollup\dist\rollup.js:5819:34)
    at value.forEach.child (C:\Users\Hely\WebstormProjects\SysmarComponents\node_modules\rollup\dist\rollup.js:5845:38)
    at Array.forEach (native)
    at keys.forEach.key (C:\Users\Hely\WebstormProjects\SysmarComponents\node_modules\rollup\dist\rollup.js:5845:11)
    at Array.forEach (native)

_please describe the error that you encountered_

#### How To Reproduce

Just use any component of primeng and then try to run 'npm packager'

#### Expected Behaviour

Every package exported or at least a file where you can add the exported files

#### Version Information

```
ng-packagr: v1.2.0
node: v8.2.1
@angular: v4.4.4node
rxjs: 5.4.3
zone.js: 0.8.18
primeng: 2.0.6

**Comment by WilliamEddy** [comment]
I am also encountering this issue when using ng2-smart-table. This bug is blocking the inclusion of the ng2-smart-table library in my own component library.

**Comment by dherges** [comment]
Hi, can you please check #129 and see if the question is answered there?

**Comment by stevie6410** [comment]
I am having this same issue with PrimeNg. I have looked at #129 but unfortunately I am none the wiser as to fix the issue. From what I have read I believe the issue is down to PrimeNg using commonjs and not ES5? 

Here is a minimal repro using the ng-packaged example. Could someone please give some clear direction on how to fix this build issue. This is my first attempt at an angular library and I am not familiar enough with this process.
https://github.com/stevie6410/ng-packaged

Thanks

**Comment by DavidParks8** [comment]
You should be able to build with primeng by utilizing the following addition to your ng-package config:
```
  {
    "lib": {
      "externals": {
        "primeng/primeng": "primeng"
      }
    }
  }
```

**Comment by vZanchiV** [comment]
thx DavidParks8 , your solution work very weel !!

**Comment by dherges** [comment]
Ok, cool. I added this issue to the documentation at linked it from the "working with third-party deps" issue. Should there still be questions, please command and/or re-open!

**Comment by zealitude** [comment]
For  "primeng/primeng": "primeng" only work for component
I use following setting for messageservice
I would like to see if there any better solution for wildcard everything

`  "ngPackage": {
    "lib": {
      "externals": {
        "primeng/primeng": "primeng",
        "primeng/components/common/messageservice": "primeng/components/common/messageservice",
      }
    }
  }`
