### ISSUE TITLE
PrimeNg Causes Build to Fail

### ISSUE THREAD

**Issue by stevie6410** [dherges/ng-packagr#176]
## Type of Issue

```
[ X ] Bug Report
[ ] Feature Request
```

## Description

Based on the sample application, simply by adding a primeNg module, it causes the build to fail. 

I guess that this is related, but not sure what to do with respect to ng-packagr.
https://github.com/rollup/rollup/issues/737

#### How To Reproduce

npm install primng
import a primeng module into the lib module
npm run build:lib

#### Expected Behaviour

Successful build with primeng as an external dependency 

#### Version Information

```
ng-packagr: v1.4.1
node: v8.6.0
@angular: v4.4.0
```

Repo here https://github.com/stevie6410/ng-packaged

```
$ ng-packagr
Building Angular library

BUILD ERROR
'PanelModule' is not exported by node_modules\primeng\primeng.js
Error: 'PanelModule' is not exported by node_modules\primeng\primeng.js
    at error (C:\src\git\ng-packaged\node_modules\rollup\dist\rollup.js:185:14)
    at Module.error (C:\src\git\ng-packaged\node_modules\rollup\dist\rollup.js:8390:3)
    at Module.trace (C:\src\git\ng-packaged\node_modules\rollup\dist\rollup.js:8487:10)
    at ModuleScope.findVariable (C:\src\git\ng-packaged\node_modules\rollup\dist\rollup.js:8093:22)
    at Node.bind (C:\src\git\ng-packaged\node_modules\rollup\dist\rollup.js:6996:31)
    at eachChild.child (C:\src\git\ng-packaged\node_modules\rollup\dist\rollup.js:5819:34)
    at value.forEach.child (C:\src\git\ng-packaged\node_modules\rollup\dist\rollup.js:5845:38)
    at Array.forEach (<anonymous>)
    at keys.forEach.key (C:\src\git\ng-packaged\node_modules\rollup\dist\rollup.js:5845:11)
    at Array.forEach (<anonymous>)
```

**Comment by stevie6410** [comment]
Just noticed that this is a dup of #142
