### ISSUE TITLE
Build stuck if @progress dependency included

### ISSUE THREAD

**Issue by IAfanasov** [dherges/ng-packagr#221]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
Build stuck if @progress dependency included
console messages are:

Building Angular library
Generating bundle for valhalla-engine

I waited for ~30 minutes

#### How To Reproduce

`git clone https://github.com/IAfanasov/ng-packagr-kendo-issue.git
npm i
npm run packagr`

#### Expected Behaviour

finished build

#### Version Information

```
ng-packagr: v1.4.1 and 1.5.0-rc.1 are tested
node: v8.3.0
@angular: v4.3.6
rxjs:
zone.js:
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by dherges** [comment]
There was a similar issue in #100 

If this is an issue with kendo ui, please ask their support. The minimal repro needed to investigate this would be sources of kendo's code to understand what causes heap out of memory. It looks like an issue with the sourcemaps of kendo. As kendo offers commercial support, I'd redirect you to them.

**Comment by IAfanasov** [comment]
Hi @dherges !
Thanks for answer!

I tried to comment line in compiled file node_modules/ng-packagr/lib/bundler.js
//yield sorcery_1.remapSourceMap(artifactPaths.es2015);

Now it fails with error

BUILD ERROR
Cannot read property 'type' of undefined
```
TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (/Users/iafanasov/Sources/Valhalla/Valhalla.SPA.Engine/node_modules/typescript/lib/typescript.js:9341:17)
    at assignContextualParameterTypes (/Users/iafanasov/Sources/Valhalla/Valhalla.SPA.Engine/node_modules/typescript/lib/typescript.js:41653:25)
    at checkFunctionExpressionOrObjectLiteralMethod (/Users/iafanasov/Sources/Valhalla/Valhalla.SPA.Engine/node_modules/typescript/lib/typescript.js:41949:29)
    at checkExpressionWorker (/Users/iafanasov/Sources/Valhalla/Valhalla.SPA.Engine/node_modules/typescript/lib/typescript.js:42960:28)
    at checkExpression (/Users/iafanasov/Sources/Valhalla/Valhalla.SPA.Engine/node_modules/typescript/lib/typescript.js:42899:42)
    at checkExpressionCached (/Users/iafanasov/Sources/Valhalla/Valhalla.SPA.Engine/node_modules/typescript/lib/typescript.js:42780:38)
    at checkReturnStatement (/Users/iafanasov/Sources/Valhalla/Valhalla.SPA.Engine/node_modules/typescript/lib/typescript.js:45419:54)
    at checkSourceElement (/Users/iafanasov/Sources/Valhalla/Valhalla.SPA.Engine/node_modules/typescript/lib/typescript.js:46764:28)
    at Object.forEach (/Users/iafanasov/Sources/Valhalla/Valhalla.SPA.Engine/node_modules/typescript/lib/typescript.js:1506:30)
    at checkBlock (/Users/iafanasov/Sources/Valhalla/Valhalla.SPA.Engine/node_modules/typescript/lib/typescript.js:44564:16)
```

Just want to know if commenting of `remapSourceMap` could lead to this error.

**Comment by skorunka** [comment]
@IAfanasov hi, did you solve this problem? thank you.

**Comment by IAfanasov** [comment]
@skorunka nope. started my lib without @progress

**Comment by skorunka** [comment]
What helped me, was to add all the peerDepenedencioes(incl @progress) to ng-package.josn as externals:

```
{
	"$schema": "../node_modules/ng-packagr/ng-package.schema.json",
	"dest": "../dist/my-lib",
	"lib": {
		"entryFile": "../ts/src/public_api.ts",
		"externals": {
			"@progress/kendo-angular-buttons": "@progress/kendo-angular-buttons",
			"@progress/kendo-angular-dateinputs": "@progress/kendo-angular-dateinputs",
			"@progress/kendo-angular-dropdowns": "@progress/kendo-angular-dropdowns",
			"@progress/kendo-angular-excel-export": "@progress/kendo-angular-excel-export",
			"@progress/kendo-angular-grid": "@progress/kendo-angular-grid",
			"@progress/kendo-angular-inputs": "@progress/kendo-angular-inputs",
			"@progress/kendo-angular-intl": "@progress/kendo-angular-intl",
			"@progress/kendo-angular-l10n": "@progress/kendo-angular-l10n",
			"@progress/kendo-data-query": "@progress/kendo-data-query",
			"@progress/kendo-drawing": "@progress/kendo-drawing"
		}
	}
}
```
