### ISSUE TITLE
build failed when using Hammerjs

### ISSUE THREAD

**Issue by sheikalthaf** [dherges/ng-packagr#262]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

_please describe the error that you encountered_

#### How To Reproduce

```javascript
const hammertime = new Hammer(this.forTouch.nativeElement);
      hammertime.get('pan').set({ direction: Hammer.DIRECTION_HORIZONTAL });
```
when using hammerjs in my component error occors  

#### Expected Behaviour

```
BUILD ERROR
Error at C:/Users/Sheik Althaf/Documents/angular/resTesting/.ng_pkg_build/res-testing/ts/src/app/shared/@ngu/carousel/ngx-carousel
/ngx-carousel.component.ts:318:30: Cannot find name 'Hammer'.
Error at C:/Users/Sheik Althaf/Documents/angular/resTesting/.ng_pkg_build/res-testing/ts/src/app/shared/@ngu/carousel/ngx-carousel
/ngx-carousel.component.ts:319:46: Cannot find name 'Hammer'.
Error: Error at C:/Users/Sheik Althaf/Documents/angular/resTesting/.ng_pkg_build/res-testing/ts/src/app/shared/@ngu/carousel/ngx-c
arousel/ngx-carousel.component.ts:318:30: Cannot find name 'Hammer'.
Error at C:/Users/Sheik Althaf/Documents/angular/resTesting/.ng_pkg_build/res-testing/ts/src/app/shared/@ngu/carousel/ngx-carousel
/ngx-carousel.component.ts:319:46: Cannot find name 'Hammer'.
    at new UserError (C:\Users\Sheik Althaf\Documents\angular\resTesting\node_modules\ng-packagr\node_modules\@angular\tsc-wrapped
\src\tsc.js:27:28)
    at check (C:\Users\Sheik Althaf\Documents\angular\resTesting\node_modules\ng-packagr\node_modules\@angular\tsc-wrapped\src\tsc
.js:93:15)
    at Tsc.typeCheck (C:\Users\Sheik Althaf\Documents\angular\resTesting\node_modules\ng-packagr\node_modules\@angular\tsc-wrapped
\src\tsc.js:173:9)
    at C:\Users\Sheik Althaf\Documents\angular\resTesting\node_modules\ng-packagr\node_modules\@angular\tsc-wrapped\src\main.js:12
2:23
    at <anonymous>
```

#### Version Information

```
ng-packagr: v1.5.0
node: v8.9.0
@angular: v4.2.3
rxjs: 5.1.0
zone.js: 0.8.4
hammerjs: 2.0.8
```

**Comment by dherges** [comment]
Hi @sheikalthaf,

can you please check #129?

There, lots of examples of configuring `lib.externals` are given. Can you please check what module id is needed for hammertime? If the build then still fails, please give us at least your configuration (ng-package.json, ...) or a GitHub repo that reproduces the error.

Thanks!

**Comment by clemtoy** [comment]
Hi @sheikalthaf,

Did you find what to write in lib.externals?

Thanks

**Comment by sheikalthaf** [comment]
@dherges Hi,
     my json looks like this.
```javascript
{
  "lib": {
    "entryFile": "src/public_api.ts",
    "externals": {
      "Hammer": "Hammer"
    }
  }
}
```

but still i'm getting an error

```javascript
BUILD ERROR
projects/carousel/src/lib/ngu-carousel/ngu-carousel.component.ts(380,30): error TS2304: Cannot find name 'Hammer'.
projects/carousel/src/lib/ngu-carousel/ngu-carousel.component.ts(381,46): error TS2304: Cannot find name 'Hammer'.

Error: projects/carousel/src/lib/ngu-carousel/ngu-carousel.component.ts(380,30): error TS2304: Cannot find name 'Hammer'.
projects/carousel/src/lib/ngu-carousel/ngu-carousel.component.ts(381,46): error TS2304: Cannot find name 'Hammer'.

    at Object.<anonymous> (E:\Angular\Library\ngu-carousel\node_modules\ng-packagr\lib\ngc\compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at E:\Angular\Library\ngu-carousel\node_modules\ng-packagr\lib\ngc\compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (E:\Angular\Library\ngu-carousel\node_modules\ng-packagr\lib\ngc\compile-source-files.js:3:12)
    at Object.compileSourceFiles (E:\Angular\Library\ngu-carousel\node_modules\ng-packagr\lib\ngc\compile-source-files.js:19:12)
    at Object.<anonymous> (E:\Angular\Library\ngu-carousel\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:26:32)
    at Generator.next (<anonymous>)
    at E:\Angular\Library\ngu-carousel\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
```
