### ISSUE TITLE
Can't import 3rd party library ng2-file-upload

### ISSUE THREAD

**Issue by crowmagnumb** [dherges/ng-packagr#300]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I am trying to inclued ```ng2-file-upload``` into  a bundle but I get the following ...

```
BUILD ERROR
'FileUploader' is not exported by node_modules/ng2-file-upload/index.js
Error: 'FileUploader' is not exported by node_modules/ng2-file-upload/index.js
    at error (/Users/ken/dev/animalus/tools/ng-packagr/node_modules/rollup/dist/rollup.js:185:14)
    at Module.error (/Users/ken/dev/animalus/tools/ng-packagr/node_modules/rollup/dist/rollup.js:14271:3)
    at Module.trace (/Users/ken/dev/animalus/tools/ng-packagr/node_modules/rollup/dist/rollup.js:14368:10)
    at ModuleScope.findVariable (/Users/ken/dev/animalus/tools/ng-packagr/node_modules/rollup/dist/rollup.js:13978:22)
    at Scope.findVariable (/Users/ken/dev/animalus/tools/ng-packagr/node_modules/rollup/dist/rollup.js:11543:33)
    at FunctionScope.findVariable (/Users/ken/dev/animalus/tools/ng-packagr/node_modules/rollup/dist/rollup.js:11543:33)
    at Scope.findVariable (/Users/ken/dev/animalus/tools/ng-packagr/node_modules/rollup/dist/rollup.js:11543:33)
    at Node._bindVariableIfMissing (/Users/ken/dev/animalus/tools/ng-packagr/node_modules/rollup/dist/rollup.js:12629:31)
    at Node.bindNode (/Users/ken/dev/animalus/tools/ng-packagr/node_modules/rollup/dist/rollup.js:12624:8)
    at Node.bind (/Users/ken/dev/animalus/tools/ng-packagr/node_modules/rollup/dist/rollup.js:10970:8)
```

I have tried adding it to externals with ...

```
        "externals": {
            "@animalus/ng-utils": "ng-utils",
            "@animalus/ng-date-utils": "ng-date-utils",
            "ng2-file-upload": "ng2-file-upload"
        }
```

... but that doesn't work. It is related to this [issue](https://github.com/valor-software/ng2-file-upload/issues/584) but I can't figure out how to implement that in ng-packagr as that config file is not exposed.

#### Version Information

```
ng-packagr: v2.0.0-rc.0
node: v8.x.y
@angular: v5.0.0
rxjs:
zone.js:
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by crowmagnumb** [comment]
Ah, the answer was in that link above. I ignored it at first because the person who responded to the answer said it didn't work. What I did to make it compile was change the import from ...

```
import {FileUploader} from 'ng2-file-upload';
```

...to ...

```
import {FileUploader} from 'ng2-file-upload/file-upload/file-uploader.class';
```

I have no idea yet if it works once I use this library but I got past that compilation problem so I'm going to close this.
