### ISSUE TITLE
Can't use lodash with this library

### ISSUE THREAD

**Issue by Itrulia** [dherges/ng-packagr#365]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Rollup throws a build error when compiling to FESM15

Error thrown:

```
Running ngc
Compiling to FESM15

BUILD ERROR
'forEach' is not exported by node_modules/lodash/lodash.js
Error: 'forEach' is not exported by node_modules/lodash/lodash.js
    at error (/home/talleane/Documents/play-utility/node_modules/rollup/dist/rollup.js:185:14)
    at Module.error (/home/talleane/Documents/play-utility/node_modules/rollup/dist/rollup.js:16526:3)
    at Module.trace (/home/talleane/Documents/play-utility/node_modules/rollup/dist/rollup.js:16623:10)
    at ModuleScope.findVariable (/home/talleane/Documents/play-utility/node_modules/rollup/dist/rollup.js:13965:22)
    at Node._bindVariableIfMissing (/home/talleane/Documents/play-utility/node_modules/rollup/dist/rollup.js:12626:31)
    at Node.bindNode (/home/talleane/Documents/play-utility/node_modules/rollup/dist/rollup.js:12621:8)
    at Node.bind (/home/talleane/Documents/play-utility/node_modules/rollup/dist/rollup.js:11005:8)
    at eachChild.child (/home/talleane/Documents/play-utility/node_modules/rollup/dist/rollup.js:11024:34)
    at value.forEach.child (/home/talleane/Documents/play-utility/node_modules/rollup/dist/rollup.js:11039:38)
    at Array.forEach (<anonymous>)
```

#### How To Reproduce

first install lodash

```bash
npm install lodash
```

In your code

```typescript
import {forEach} from "lodash";
console.log(forEach);
```

#### Expected Behaviour

Expected that no error is thrown and a packge is generated

#### Version Information

```
ng-packagr: v1.6.0
node: v8.6.0
@angular: v4.2.4
rxjs: 5.4.2
zone.js: 0.8.14
lodash: 4.17.4
```

**Comment by deebloo** [comment]
@Itrulia you need to configured lodash as externals in your config.

**Comment by Itrulia** [comment]
my tsconfig or ng-packagr?  tsconfig is standard `@angular/cli` one. `ng-package.json` is just

```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
      "entryFile": "public_api.ts"
  }
}
```

`angular/cli` one looks like this:

```
{
    "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
    "project": {
      "name": "play-state"
    },
    "apps": [{
      "root": "public",
      "outDir": "public_dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "",
      "styles": [
        "styles.scss"
      ],
      "scripts": [],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }],
    "e2e": {
      "protractor": {
        "config": "./protractor.conf.js"
      }
    },
    "lint": [{
        "project": "public/tsconfig.app.json",
        "exclude": "**/node_modules/**"
      },
      {
        "project": "public/tsconfig.spec.json",
        "exclude": "**/node_modules/**"
      },
      {
        "project": "e2e/tsconfig.e2e.json",
        "exclude": "**/node_modules/**"
      }
    ],
    "test": {
      "karma": {
        "config": "./karma.conf.js"
      }
    },
    "defaults": {
      "styleExt": "scss",
      "component": {
        "viewEncapsulation": "Emulated",
        "changeDetection": "OnPush"
      }
    }
  }

```

**Comment by DavidParks8** [comment]
You need to add the correct lodash external to your ngpackagr config. Alternarively, you can use ‘lodash-es’ and the build should succeed.

**Comment by dherges** [comment]
Hi all,

yes, see #129.

**Comment by Itrulia** [comment]
Will look in to it in my 20% time after the christmas party. Thanks!

**Comment by tommueller** [comment]
@Itrulia I was a bit puzzled about this myself, as it isn't very well documented so far. I did finally manage to solve by adding this to my ng-package.json:
```json
"externals": {
    "lodash": "./node_modules/lodash/index.js"
}
```

Cheers,
Tom

**Comment by Itrulia** [comment]
Thanks this works beautifully :)

**Comment by Itrulia** [comment]
Whoops, didn't meant to close, since I want to document stuff when I am back working on my package :D

**Comment by metodribic** [comment]
I have the following ng-packagr configuration inside `modules/<my-package>/package.json`:
```
"ngPackage": {
    "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
    "dest": "dist/auth",
    "workingDirectory": "../../.ng_build",
    "externals": {
      "lodash": "./node_modules/lodash/index.js"
    },
    "lib": {
      "entryFile": "index.ts"
    }
  }
```
and I'm running build from root with `ng-packagr -p modules/<my-package>/package.json`
but I'm still getting the following error:
```
BUILD ERROR
'merge' is not exported by modules/<my-package>/node_modules/lodash/lodash.js
```
Any ideas?

**Comment by metodribic** [comment]
Oh nevermind. I figure it out `externals` has to be inside `lib` property
