### ISSUE TITLE
Cannot read property 'localTypeParameters' of undefined at Compiling to FESM5

### ISSUE THREAD

**Issue by silberjan** [dherges/ng-packagr#367]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

During the pipeline, at the step `Compiling to FESM5` i get the following error: 

``` 
BUILD ERROR
Cannot read property 'localTypeParameters' of undefined
TypeError: Cannot read property 'localTypeParameters' of undefined
    at checkTypeReferenceNode (C:\dev\targomo\typescript\client\node_modules\typescript\lib\typescript.js:39603:138)
    at checkSourceElement (C:\dev\targomo\typescript\client\node_modules\typescript\lib\typescript.js:42794:28)
    at Object.forEach (C:\dev\targomo\typescript\client\node_modules\typescript\lib\typescript.js:1496:30)
    at checkUnionOrIntersectionType (C:\dev\targomo\typescript\client\node_modules\typescript\lib\typescript.js:39636:16)
    at checkSourceElement (C:\dev\targomo\typescript\client\node_modules\typescript\lib\typescript.js:42807:28)
    at checkSourceElement (C:\dev\targomo\typescript\client\node_modules\typescript\lib\typescript.js:42828:28)
    at checkSourceElement (C:\dev\targomo\typescript\client\node_modules\typescript\lib\typescript.js:42814:28)
    at checkJSDocComment (C:\dev\targomo\typescript\client\node_modules\typescript\lib\typescript.js:40401:21)
    at checkSourceElement (C:\dev\targomo\typescript\client\node_modules\typescript\lib\typescript.js:42812:28)
    at Object.forEach (C:\dev\targomo\typescript\client\node_modules\typescript\lib\typescript.js:1496:30)
```

The only issue with this stack trace is over here: https://github.com/Microsoft/TypeScript/issues/17377

However i checked my code and it does not contain any of the relevant JS Doc tokens. All my externals are also declared properly (or are they?):

``` json
 "externals": {
      "@angular/material": "ng.material",
      "@targomo/core": "tgm",
      "@targomo/common": "tgm-common",
      "mapbox-gl": "mapboxgl",
      "ng2-nvd3": "ng2-nvd3",
      "rxjs": "rxjs",
      "d3": "d3",
      "@angular/core": "ng.core",
      "@angular/cdk": "ng.cdk",
      "@angular/cdk/a11y": "ng.cdk.a11y",
      "@angular/cdk/accordion": "ng.cdk.accordion",
      "@angular/cdk/bidi": "ng.cdk.bidi",
      "@angular/cdk/coercion": "ng.cdk.coercion",
      "@angular/cdk/collections": "ng.cdk.collections",
      "@angular/cdk/keycodes": "ng.cdk.keycodes",
      "@angular/cdk/layout": "ng.cdk.layout",
      "@angular/cdk/observers": "ng.cdk.observers",
      "@angular/cdk/overlay": "ng.cdk.overlay",
      "@angular/cdk/platform": "ng.cdk.platform",
      "@angular/cdk/portal": "ng.cdk.portal",
      "@angular/cdk/rxjs": "ng.cdk.rxjs",
      "@angular/cdk/scrolling": "ng.cdk.scrolling",
      "@angular/cdk/stepper": "ng.cdk.stepper",
      "@angular/cdk/table": "ng.cdk.table",
      "@angular/flex-layout": "ng.flex-layout",
      "color": "color",
      "d3-scale": "d3-scale",
      "d3-scale-chromatic": "d3-scale-chromatic",
      "turf": "turf"
    }
```

#### How To Reproduce

I have no idea what is causing this issue so i also have no idea how to repro.

#### Expected Behaviour

Dont fail at `Compiling to FESM5`

#### Version Information

```
ng-packagr: v2.0.0-rc.4
node: v8.9.0
@angular: v5.0.1
rxjs: 5.5.2
```

**Comment by dherges** [comment]
Hi, what Typescript version?

Cheers, David

**Comment by silberjan** [comment]
2.4.2

I just noticed, that I did not declare turf properly in the externals. It's `@turf/turf` instead of `turf`. In the end this lib contained some jsdoc lines that broke the process.
