### ISSUE TITLE
[2.0.0-rc.6] TypeScript 2.6 clashes with tsickle 0.25.x

### ISSUE THREAD

**Issue by stephenlautier** [dherges/ng-packagr#397]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

After update from version 2.0.0-rc.5 to version 2.0.0-rc.6 im getting several issues, as below.

When building with rc.6
```
[1] Bundling to FESM15
[1] 'Injector', 'ErrorHandler', 'PipeTransform', 'OnDestroy', 'Provider' and 'ModuleWithProviders' are imported from external module '@angular/core' but never used
[1] 'Observable' is imported from external module 'rxjs/Observable' but never used
[1] 'HttpResponse' and 'HttpErrorResponse' are imported from external module '@angular/common/http' but never used
[1] 'NavigationExtras' is imported from external module '@angular/router' but never used
[1] 'TranslationChangeEvent' is imported from external module '@ngx-translate/core' but never used
[1] 'Subscription' is imported from external module 'rxjs/Subscription' but never used
[1]
[1] BUILD ERROR
[1] 'NonArray' is not exported by .ng_pkg_build\odin-ngx.core\out\utils\object\object.js
[1] Error: 'NonArray' is not exported by .ng_pkg_build\odin-ngx.core\out\utils\object\object.js
[1]     at error (C:\dev\git\odin.ngx.core\node_modules\rollup\dist\rollup.js:189:14)
[1]     at Module.error (C:\dev\git\odin.ngx.core\node_modules\rollup\dist\rollup.js:16532:3)
[1]     at Module.traceExport (C:\dev\git\odin.ngx.core\node_modules\rollup\dist\rollup.js:16655:10)
[1]     at NamespaceVariable.module.getExports.concat.forEach.name (C:\dev\git\odin.ngx.core\node_modules\rollup\dist\rollup.js:5671:36)
[1]     at Array.forEach (<anonymous>)
[1]     at new NamespaceVariable (C:\dev\git\odin.ngx.core\node_modules\rollup\dist\rollup.js:5670:55)
[1]     at Module.namespace (C:\dev\git\odin.ngx.core\node_modules\rollup\dist\rollup.js:16578:31)
[1]     at modules.forEach.module (C:\dev\git\odin.ngx.core\node_modules\rollup\dist\rollup.js:18187:29)
[1]     at Array.forEach (<anonymous>)
[1]     at Bundle$$1.deconflict (C:\dev\git\odin.ngx.core\node_modules\rollup\dist\rollup.js:18179:16)
[1]
```
(added as screenshot below, perhaps to see it better)

When building with rc.5
```
[1] Bundling to FESM15
[1] Bundling to FESM5
[1] Bundling to UMD
[1] Minifying UMD bundle
[1] Dropping unreachable code [0:1819,4]
[1] Declarations in unreachable code! [0:1819,4]
[1] Dropping unreachable code [0:1832,4]
[1] Declarations in unreachable code! [0:1832,4]
[1] Remapping source maps
[1] Copying staged files
[1] Writing package metadata
[1] Built @odin/ngx.core
[1] Built Angular Package!
[1]  - from: C:\dev\git\odin.ngx.core
[1]  - to:   C:\dev\git\odin.ngx.core\dist
```

We have another library is throwing a similar error as well, not just this one.

The code its complaining about its very simplistic

```
// utils/object/object.ts
export type NonArray = { forEach?: void };
...

// index.ts
export { NonArray, PartialObject } from "./utils/object/object";
```

Entry file configured as:

```json
{
	"$schema": "./node_modules/ng-packagr/ng-package.schema.json",
	"lib": {
		"entryFile": "./src/index.ts",
		"externals": {
			"@ngx-translate/core": "ngxTranslate.core",
			"localforage": "localforage",
			"localize-router": "localize.router",
			"lodash": "lodash",
			"moment": "moment"
		}
	}
}
```

Also the warnings given by rollup, not sure if they are thrown because the build is failing, but the types specified as not used are actually being used.

#### How To Reproduce

_for bugs: please include instructions how to reproduce_
Simply `ng-packagr -p ng-package.json`

_Can you reproduce the error in the integration tests in ng-packagr?_
_If possible, take a look at the [`integration/samples`](./integration/samples) and try to break one of these builds!_

#### Expected Behaviour

Library should build successfully

#### Version Information

```
ng-packagr: 2.0.0-rc.6
@angular/*: 5.1.0
typescript: 2.6.2
rxjs: 5.5.5
node: 8.9.0
npm/yarn: 5.4.2
```

![2017-12-11 16_00_59-object ts - odin ngx core - visual studio code](https://user-images.githubusercontent.com/3908723/33838248-389f114c-de8f-11e7-8848-fef101b3c552.png)

**update 1:** one thing i observed is that both libraries which are failing, they are failing on an `export type` alias which nothing gets generated as JS (since its just a `type`)

**update 2:** tsc alone it works in my project, tried to copy the type and used it in `integration/sample` and so far no errors

**Comment by alan-agius4** [comment]
The issue seems to be related to `TypeScript 2.6` and `tsickle`. With `TypeScript 2.5.X` it works fine.

As of now `@angular/compiler-cli` and `tsickle` don't yet support `2.6` in-fact their `peerDependencies` are both set to "typescript": ">=2.4.2 <2.6"

**Comment by alan-agius4** [comment]
The `CHANGELOG` seems to be pointing to use wrong TypeScript Versions.

#398 398

**Comment by dherges** [comment]
Yep.

- Angular 5.0.x: typescript ~2.4.2
- Angular 5.1.x: typescript ~2.5.0

It was said that TypeScript 2.6 doesn't yet work with Angular. Changelog message is wrong.

**Comment by dherges** [comment]
@stephenlautier Best guess: if it's just a version mismatch, lucky you!

If not, can you try to break one of the `integration/samples` builds in this repo? It will help to find what is wrong.

**Comment by stephenlautier** [comment]
Yes, my typescript is `2.6.2` as I stated above, so that's the issue as @alan-agius4 mentioned. 
By either using `rc.5` and `TS 2.6.2` or `rc.6` and `~2.5.3` as angular suggests both works.

It would be nice if its possible to switch off closure since I would prefer to use the latest TS instead of closure (since i dont care about it at this point)

**Comment by alan-agius4** [comment]
While Angular 5 doesn’t yet offer office support for Typescript 2.6 it does
work if you don’t use tsickle.

Also as a matter of fact also at work we use Angular 4 with Typescript 2.6
and we have over 12 libraries and never encountered any issues realated to
TypeScript not matching the suggested by Angular.

**Comment by dherges** [comment]
closing the issue. Seems to be solved in the latest rc.
