### ISSUE TITLE
[Bug] Comma at end in styleUrl will not compile.

### ISSUE THREAD

**Issue by Lexanius** [dherges/ng-packagr#407]
## Type of Issue

[x] Bug Report

## Description
I get the following error:
```
ng-packagr -p package.json

Building Angular Package
Building from sources for entry point 'adilo-dashboard'
Cleaning build directory
Extracting templateUrl and styleUrls
Processing assets

BUILD ERROR
Cannot inline stylesheet absolute-path\in\project\,
Error: Cannot inline stylesheet absolute-path\in\project\,
    at Object.<anonymous> ([...]\node_modules\ng-packagr\lib\steps\assets.js:87:31)
    at Generator.throw (<anonymous>)
    at rejected ([...]\node_modules\ng-packagr\lib\steps\assets.js:5:65)
    at <anonymous>
```

### Not Compile
```
/**
 * @export
 */
@Component({
    selector: 'my-component',
    templateUrl: 'my-component.html',
    styleUrls: [
        'my-component.scss',
    ],
})
export class MyComponent {}
```

### Compile
```
/**
 * @export
 */
@Component({
    selector: 'my-component',
    templateUrl: 'my-component.html',
    styleUrls: [
        'my-component.scss'
    ],
})
export class MyComponent {}
```

## Whats the different

If there is a comma(,) behind the styleUrl in the component it wont compile in packagr but in angular-cli
See: styleUrls: [ 'my-component.scss' -->,<-- ],
#### Version Information

```
ng-packagr: ^2.0.0-rc.6
@angular/*: ~5.0.0
typescript: "~2.4.2"
rxjs: "^5.5.5",
node: 9.3.0
npm: 5.5.1
```

**Comment by tretne** [comment]
I have the same issue with components that references multiple stylesheets in `styleUrls`:

Steps to reproduce:
In the [`integration/samples/core`](./integration/samples/core):
- Add the files `a.css` and `b.css` (both can be empty)
- Add the property `styleUrls: ['a.css','b.css']` to `angular.componentn.ts`
- Run `yarn test` (or `node .\dist\cli\main.js -p .\integration\samples\core\ng-package.json`)

```bash
Building Angular Package
[debug] Found primary entry point: @sample/core
[debug] rimraf D:\git\demos\ng-packagr\integration\samples\core\dist
Building from sources for entry point '@sample/core'
Cleaning build directory
[debug] rimraf D:\git\demos\ng-packagr\integration\samples\core\.ng_pkg_build\sample-core\out
[debug] rimraf D:\git\demos\ng-packagr\integration\samples\core\.ng_pkg_build\sample-core\stage
Extracting templateUrl and styleUrls
Processing assets
[debug] Render styles for D:\git\demos\ng-packagr\integration\samples\core\src\a.css
[debug] reading css from D:\git\demos\ng-packagr\integration\samples\core\src\a.css
[debug] Render styles for D:\git\demos\ng-packagr\integration\samples\core\src\,
[debug] reading css from D:\git\demos\ng-packagr\integration\samples\core\src\,
[debug] Render styles for D:\git\demos\ng-packagr\integration\samples\core\src\b.css
[debug] reading css from D:\git\demos\ng-packagr\integration\samples\core\src\b.css

BUILD ERROR
Cannot inline stylesheet D:\git\demos\ng-packagr\integration\samples\core\src\,
Error: Cannot inline stylesheet D:\git\demos\ng-packagr\integration\samples\core\src\,
    at Object.<anonymous> (D:\git\demos\ng-packagr\dist\lib\steps\assets.js:87:31)
    at Generator.throw (<anonymous>)
    at rejected (D:\git\demos\ng-packagr\dist\lib\steps\assets.js:5:65)
    at <anonymous>

Build failed. The working directory was not pruned. Files are stored at {ngPackage.workingDirectory}.
```

**Comment by Ks89** [comment]
It's ok with 1.6.0, but I have the same issue with 2.0.0-rc.8.

I confirm that it is related to #424, because also multiple styles aren't working.

**Comment by dherges** [comment]
Fix in rc.9
