### ISSUE TITLE
Sourcemap consumers fails when reading FESM5 bundle

### ISSUE THREAD

**Issue by dherges** [dherges/ng-packagr#45]
Repro / Error:

```bash
$ ng serve --extract-css
** NG Live Development Server is listening on localhost:4200, open your browser on http://
localhost:4200 **
 92% chunk asset optimization<project>\node_modules\source-map\lib\source-node.js:95
          var code = nextLine.substr(0, mapping.generatedColumn -
                             ^

TypeError: Cannot read property 'substr' of undefined
    at Function.<anonymous> (<project>\node_modules\source-map\lib\source-node.js:95:30)
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (<project>\node_modules\source-map\lib\source-map-consumer.js:155:14)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (<project>\node_modules\source-map\lib\source-node.js:80:24)
    at SourceMapSource.node (<project>\node_modules\webpack-sources\lib\SourceMapSource.js:42:20)
    at ReplaceSource.node (<project>\node_modules\webpack-sources\lib\ReplaceSource.js:69:29)
    at CachedSource.node (<project>\node_modules\webpack-sources\lib\CachedSource.js:12:23)
    at <project>\node_modules\webpack-sources\lib\ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (<project>\node_modules\webpack-sources\lib\ConcatSource.js:39:60)
    at <project>\node_modules\webpack-sources\lib\ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (<project>\node_modules\webpack-sources\lib\ConcatSource.js:39:60)
    at <project>\node_modules\webpack-sources\lib\ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (<project>\node_modules\webpack-sources\lib\ConcatSource.js:39:60)
error Command failed with exit code 1.
```

Cause:

in the `<library>.es5.js`:
```js
//# sourceMappingURL=<library>.js.map
//# sourceMappingURL=<library>.js.map
```

Changing manually to `<library>.es5.js.map` lets the build pass (at least).

**Comment by dherges** [comment]
Closed by #50
