### ISSUE TITLE
[2.0.0-rc.8] tsickle version mis-match

### ISSUE THREAD

**Issue by ctaepper** [dherges/ng-packagr#452]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
```bash
➜  core git:(master) ✗ npm run build:modules

> ng-packagr

module.js:538
    throw err;
    ^

Error: Cannot find module 'tsickle/src/tsickle'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/***/packages/core/node_modules/ng-packagr/lib/util/ngc-patches.js:12:17)

```

#### How To Reproduce

just following the instructions...

#### Expected Behaviour

the file `node_modules/ng-packagr/lib/util/ngc-patches.js` contains the following:
```js
const tsickle = require("tsickle/src/tsickle");
```
if i change that manually to the following, everything works as expected
```js
const tsickle = require("tsickle");
```

#### Version Information

```
ng-packagr: 2.0.0-rc.7
@angular/*: 5.0.5
typescript: 2.4.2
rxjs: 5.5.2
node: 8.9.1
npm: 5.6.0
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by hamedbaatour** [comment]
@dherges confirming, facing the same issue
```
$ ng-packagr
module.js:538
    throw err;
    ^
Error: Cannot find module 'tsickle/src/tsickle'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by dherges** [comment]
Hi, what `tsickle` version do you have installed?

#436

**Comment by ctaepper** [comment]
with me it is 0.24.1, so within ng-packagrs peer deps

**Comment by ctaepper** [comment]
ok so i updated manually to tsickle@0.25.6 and its working now. i can see that in this version, tsickle has its build output files next to the source files. in tsickle@0.24.1 the build output was in an separate build directory.

it seems that ng-packagr build uses tsickle@^0.25.5 because this is required in its devdependecnies. however, the peerdependencies are fine with ^0.24.0 which will not work together because of the different build folder structor

**Comment by JohnGalt1717** [comment]
FYI, this is now back with the latest version.
