### ISSUE TITLE
Cannot call a namespace ('includes')

### ISSUE THREAD

**Issue by randyaa** [dherges/ng-packagr#454]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

following the instructions here:
https://medium.com/@nikolasleblanc/building-an-angular-4-component-library-with-the-angular-cli-and-ng-packagr-53b2ade0701e

We're getting the following error:
```
> ng-packagr -p ng-package.json

Building Angular library
Generating bundle for project-name
Cleaning bundle build directory
Processing assets
Running ngc
Compiling to FESM15

BUILD ERROR
Cannot call a namespace ('includes')
Error: Cannot call a namespace ('includes')
    at error (C:\extras\code\gitlab\project-name\node_modules\rollup\dist\rollup.js:185:14)
    at Module.error (C:\extras\code\gitlab\project-name\node_modules\rollup\dist\rollup.js:16526:3)
    at Node.bindNode (C:\extras\code\gitlab\project-name\node_modules\rollup\dist\rollup.js:11918:17)
    at Node.bind (C:\extras\code\gitlab\project-name\node_modules\rollup\dist\rollup.js:11005:8)
    at eachChild.child (C:\extras\code\gitlab\project-name\node_modules\rollup\dist\rollup.js:11024:34)
    at keys.forEach.key (C:\extras\code\gitlab\project-name\node_modules\rollup\dist\rollup.js:11041:5)
    at Array.forEach (<anonymous>)
    at Node.eachChild (C:\extras\code\gitlab\project-name\node_modules\rollup\dist\rollup.js:11034:13)
    at Node.bindChildren (C:\extras\code\gitlab\project-name\node_modules\rollup\dist\rollup.js:11024:8)
    at Node.bind (C:\extras\code\gitlab\project-name\node_modules\rollup\dist\rollup.js:11004:8)
```

**Comment by randyaa** [comment]
this is coming from a component that has this import:
`import * as includes from "lodash.includes";`

i tried changing the import as name but it gives the same error

**Comment by randyaa** [comment]
switching to `import includes from "lodash.includes";` seemed to work

**Comment by svi3c** [comment]
Same problem here with [jwt-decode](https://github.com/auth0/jwt-decode). I cannot switch to the default import, since there is no default export from jwt-decode.

**Comment by svi3c** [comment]
Worked around by not using the `@types/jwt-decode` types and declaring a custom module declaration:

```
declare module "jwt-decode";
```

**Comment by fronteyes** [comment]
Can you post your complete code, @svi3c ? I have the same issue with `keycloak-js`:

`const Keycloak = require('keacloak-js');
declare module 'Keycloak';`

didn't work: 

`Invalid module name in augmentation, module 'Keycloak' cannot be found.`

**Comment by svi3c** [comment]
Hi @fronteyes,

Try it this way:

`some-declaration-file.d.ts`:
```ts
declare module "keycloak-js";
```

`some-file.ts`:
```ts
import Keycloak from "keycloak-js";
```
