### ISSUE TITLE
False expression: Host should not return a redirect source file from `getSourceFile` when building

### ISSUE THREAD

**Issue by dragonflypl** [dherges/ng-packagr#473]
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

I have a monorepo bootstraped with lerna. One package (parent) had dependency to the other (via symlink). When I try to run `ng-packagr -p package.json` on parent, I get this error:

```
C:\XXX\dev\webstack\packages\spinner>npm run build

> @XXX.gom.webstack/spinner@1.0.0-rc.0 build C:\XXX\dev\webstack\packages\spinner
> ng-packagr -p package.json && cd dist && npm pack

Building Angular Package
Building from sources for entry point '@XXX.gom.webstack/spinner'
Cleaning build directory
Extracting templateUrl and styleUrls
Processing assets
Inlining templateUrl and styleUrls
Compiling with ngc

BUILD ERROR
: Error: Debug Failure. False expression: Host should not return a redirect source file from `getSourceFile`
    at tryReuseStructureFromOldProgram (C:\XXX\dev\webstack\packages\spinner\node_modules\typescript\lib\typescript.js:70036:26)
    at Object.createProgram (C:\XXX\dev\webstack\packages\spinner\node_modules\typescript\lib\typescript.js:69763:34)
    at AngularCompilerProgram._updateProgramWithTypeCheckStXXX (C:\XXX\dev\webstack\packages\spinner\node_modules\@angular\compiler-cli\src\transformers\program.js:458:30)
    at AngularCompilerProgram.initSync (C:\XXX\dev\webstack\packages\spinner\node_modules\@angular\compiler-cli\src\transformers\program.js:383:18)
    at AngularCompilerProgram.get [as tsProgram] (C:\XXX\dev\webstack\packages\spinner\node_modules\@angular\compiler-cli\src\transformers\program.js:357:22)
    at AngularCompilerProgram.getTsProgram (C:\XXX\dev\webstack\packages\spinner\node_modules\@angular\compiler-cli\src\transformers\program.js:101:79)
    at new AngularCompilerProgram (C:\XXX\dev\webstack\packages\spinner\node_modules\@angular\compiler-cli\src\transformers\program.js:45:53)
    at Object.createProgram (C:\XXX\dev\webstack\packages\spinner\node_modules\@angular\compiler-cli\src\transformers\program.js:600:12)
    at Object.performCompilation (C:\XXX\dev\webstack\packages\spinner\node_modules\@angular\compiler-cli\src\perform_compile.js:183:22)
    at Object.<anonymous> (C:\XXX\dev\webstack\packages\spinner\node_modules\ng-packagr\lib\steps\ngc.js:164:27)

Error: : Error: Debug Failure. False expression: Host should not return a redirect source file from `getSourceFile`
    at tryReuseStructureFromOldProgram (C:\XXX\dev\webstack\packages\spinner\node_modules\typescript\lib\typescript.js:70036:26)
    at Object.createProgram (C:\XXX\dev\webstack\packages\spinner\node_modules\typescript\lib\typescript.js:69763:34)
    at AngularCompilerProgram._updateProgramWithTypeCheckStXXX (C:\XXX\dev\webstack\packages\spinner\node_modules\@angular\compiler-cli\src\transformers\program.js:458:30)
    at AngularCompilerProgram.initSync (C:\XXX\dev\webstack\packages\spinner\node_modules\@angular\compiler-cli\src\transformers\program.js:383:18)
    at AngularCompilerProgram.get [as tsProgram] (C:\XXX\dev\webstack\packages\spinner\node_modules\@angular\compiler-cli\src\transformers\program.js:357:22)
    at AngularCompilerProgram.getTsProgram (C:\XXX\dev\webstack\packages\spinner\node_modules\@angular\compiler-cli\src\transformers\program.js:101:79)
    at new AngularCompilerProgram (C:\XXX\dev\webstack\packages\spinner\node_modules\@angular\compiler-cli\src\transformers\program.js:45:53)
    at Object.createProgram (C:\XXX\dev\webstack\packages\spinner\node_modules\@angular\compiler-cli\src\transformers\program.js:600:12)
    at Object.performCompilation (C:\XXX\dev\webstack\packages\spinner\node_modules\@angular\compiler-cli\src\perform_compile.js:183:22)
    at Object.<anonymous> (C:\XXX\dev\webstack\packages\spinner\node_modules\ng-packagr\lib\steps\ngc.js:164:27)

    at Object.<anonymous> (C:\XXX\dev\webstack\packages\spinner\node_modules\ng-packagr\lib\steps\ngc.js:185:35)
    at Generator.next (<anonymous>)
    at C:\XXX\dev\webstack\packages\spinner\node_modules\ng-packagr\lib\steps\ngc.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\XXX\dev\webstack\packages\spinner\node_modules\ng-packagr\lib\steps\ngc.js:3:12)
    at Object.ngc (C:\XXX\dev\webstack\packages\spinner\node_modules\ng-packagr\lib\steps\ngc.js:149:12)
    at Object.<anonymous> (C:\XXX\dev\webstack\packages\spinner\node_modules\ng-packagr\lib\entry-point-transforms.js:49:34)
    at Generator.next (<anonymous>)
    at fulfilled (C:\XXX\dev\webstack\packages\spinner\node_modules\ng-packagr\lib\entry-point-transforms.js:4:58)
    at <anonymous>

Build failed. The working directory was not pruned. Files are stored at C:\XXX\dev\webstack\packages\spinner\.ng_pkg_build.
```

#### How To Reproduce

I'll try to reproduce it in a repo that could be published.

So far: all paths are set correctly, e.g. I have:

```
  "ngPackage": {
    "lib": {
      "entryFile": "index.ts"
    }
  }
```

Also when I pack child dependency and install tgz or install it from `npm` (i.e. when in node_modules package is already built with `ng-packgr`) or even copy paste source code of child , then everything is working ok. So it seems that when in node_modules there is a symlink, then building fails.

#### Expected Behaviour

Parent package whould be build.

Is there a way to achieve it with symlinks?

#### Version Information

```
ng-packagr: 2.0.0-rc.9
@angular/5.1.3
typescript: 2.5.3
rxjs:5.5.6
node: 8.9.3
npm: 5.6.0
```

**Comment by gmfun** [comment]
I am getting the same error. But when I move the angular package out of lerna, and symlink the libraries using relative path like below, `ng-packagr` works fine.
`package.json`
```json
    "ht-client":` "file:../ht/packages/client",
    "ht-data": "file:../ht/packages/data",
```

Build fails even when I locally install the dependent package from relative path within the lerna packages folder.

**Comment by alan-agius4** [comment]
I am experiencing the same problem and it seems that this can be solved by specifying paths in the `tsconfig.ngc.json` and baseUrl to "."

**Comment by dherges** [comment]
in `getSourceFile` of the synthesized compiler host (`createCompilerHostForSynthesizedSourceFiles(..)`):

```
<project>/node_modules/@types/webpack-sources/node_modules/source-map/source-map.d.ts
{ redirectTarget:
   SourceFileObject {
     pos: 0,
     end: 3060,
     flags: 0,
     transformFlags: undefined,
     parent: undefined,
     kind: 268,
     languageVersion: 2,
     fileName: '<project>/node_modules/@types/uglify-js/node_modules/source-map/source-map.d.ts',
  }
}
```

A monkey patch seems to be returning the `sourceFile.redirectInfo.redirectTarget` instead of the `sourceFile`.

```ts
let sourceFile = sourceFiles.find(file => file.fileName === fileName);
if (sourceFile.redirectInfo) {
    sourceFile = sourceFile.redirectInfo.redirectTarget;
}
/* furhter processing */

return sourceFile;
```
