### ISSUE TITLE
gulp-inline-ng2-template: Error with @angular/animations

### ISSUE THREAD

**Issue by ChrisProlls** [dherges/ng-packagr#51]
Because of lack of publishing lib with Angular CLI, I started to use your plugin which packages our Angular app into NPM package  that can be published. Our whole Angular application is both library and application that can be built to be hosted. My goal here is to package the application so that others applications can use our reusable components. There is the `ng-package.json` : 
```JSON
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "src": "",
  "dest": "dist",
  "workingDirectory": ".ng_build",
  "lib": {
    "entryFile": "src/public_api.ts"
  }
}
```
The `public_api.ts` only export the main module that will be imported in the other application.
```TS
export * from './app/main.module';
```

And this is our `package.json` file
```JSON
"scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build:lib": "ng-packagr",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
"dependencies": {
    "@angular/animations": "^4.1.3",
    "@angular/common": "^4.1.3",
    "@angular/compiler": "^4.1.3",
    "@angular/core": "^4.1.3",
    "@angular/forms": "^4.1.3",
    "@angular/http": "^4.1.3",
    "@angular/platform-browser": "^4.1.3",
    "@angular/platform-browser-dynamic": "^4.1.3",
    "@angular/router": "^4.1.3",
...
}
```

When I launch `npm run build:lib`, I face into this error 
```
Building Angular library from C:\_Git\SFK\src\Sfk.WebComponents\ng-package.json
fs.js:583
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\_Git\SFK\src\Sfk.WebComponents\node_modules\@angular\animations\src\my-component-tpl.html'
    at Object.fs.openSync (fs.js:583:18)
    at Object.fs.readFileSync (fs.js:490:33)
    at getFileData (C:\_Git\SFK\src\Sfk.WebComponents\node_modules\gulp-inline-ng2-template\parser.js:284:17)
    at C:\_Git\SFK\src\Sfk.WebComponents\node_modules\gulp-inline-ng2-template\parser.js:248:22
    at C:\_Git\SFK\src\Sfk.WebComponents\node_modules\async\dist\async.js:3830:24
    at replenish (C:\_Git\SFK\src\Sfk.WebComponents\node_modules\async\dist\async.js:946:17)
    at C:\_Git\SFK\src\Sfk.WebComponents\node_modules\async\dist\async.js:950:9
    at eachOfLimit (C:\_Git\SFK\src\Sfk.WebComponents\node_modules\async\dist\async.js:975:24)
    at C:\_Git\SFK\src\Sfk.WebComponents\node_modules\async\dist\async.js:980:16
    at _parallel (C:\_Git\SFK\src\Sfk.WebComponents\node_modules\async\dist\async.js:3829:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sfk@1.0.0 build:lib: `ng-packagr`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sfk@1.0.0 build:lib script 'ng-packagr'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sfk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng-packagr
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sfk
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sfk
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cgigax\AppData\Roaming\npm-cache\_logs\2017-06-08T11_01_23_336Z-debug.log
```

The log say something like this 

```
13 info lifecycle sfk@1.0.0~build:lib: Failed to exec build:lib script
14 verbose stack Error: sfk@1.0.0 build:lib: `ng-packagr`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\cgigax\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\cgigax\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

Any ideas ?

**Comment by dherges** [comment]
Hi,

this is likely an issue with [gulp-inline-ng2-template](https://github.com/ludohenin/gulp-inline-ng2-template) when it tries to inline `node_modules\@angular\animations\src\my-component-tpl.html`.

Can you give more details which source file causes the error?

**Comment by ChrisProlls** [comment]
Thanks for your rely !
I thinks the plugin parses comments, and the `my-component-tpl.html` is in comment for Angular documentation.
https://github.com/ludohenin/gulp-inline-ng2-template/issues/79

**Comment by dherges** [comment]
The issue here seems also to be that your build picks up `.d.ts` files from `node_modules`. To what is the `src` directory from `ng-package.json` configured?

```
|- package.json
|- node_modules
    |- @angular
        |- animations
            |- animations.d.ts
|- ng-package.json    # <-- does "src" point to the root folder?
|- my-lib             # <-- can you set it to here?
    |- public_api.ts
```

**Comment by ChrisProlls** [comment]
Yes the `src` point to the root folder because the `package.json` is on the root folder. As I said, my Angular project is both the library and an Angular app that can be hosted. So I have someting like that
```
|- package.json
|- node_modules
    |- @angular
        |- animations
            |- animations.d.ts
|- ng-package.json    # <-- "src" point to the root folder because of package.json
|- src                          
    |- app
        |- component1
        |- component2
    |- public_api.ts
    |- index.html
    |- main.ts
```

I've tried to move `package.json` and `ng-package.json` to the 'src' folder, and after `npm install` I face with the exact same problem. Even if I move all my components library, because my components need `@angular/animations` it would be the same after all.
