### ISSUE TITLE
embedded modules.

### ISSUE THREAD

**Issue by Cydev2306** [dherges/ng-packagr#530]
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description
Hi, I tried to use your example around embedded modules with lodash and still have an error on build

'isNil' is not exported by 'node_modules/lodash/lodash.js'.
#### How To Reproduce

create a new project with ng command
install the ng-packagr dependancy
install lodash as dev-dependancy. 

Create a fake app.service.ts
```typescript
import {Injectable} from '@angular/core';
import * as _ from 'lodash';

@Injectable()
export class AppService {

  foo(): string {
    return 'foo';
  }
  bar(): string {
    return 'bar';
  }
  foobar(param: string): number {
    let ret = 2;
    if (_.isNil(param)) {
      ret = + 1;
    }
    return ret;
  }
}

```

export it inside public_api
```typescript
export {AppService} from './src/app/app.service';
```

create the ng-package with that configuration
```json
{
  "$schema": "./node_modules/ng-packagr/package.schema.json",
  "name": "packagrTest",
  "version": "1.0.0",
  "lib": {
    "embedded": [
      "lodash"
    ],
    "umdModuleIds": {
      "lodash": "_"
    },
    "entryFile": "public_api.ts"
  }
}

```

modify build command to specify the ng-package and the command to use
```json
{
    "build": "ng-packagr -p ng-package.json"
}
```

Did i forgot something to embed lodash ?

**Comment by dherges** [comment]
Can you give access to a repro or paste the logs obtained from debug? `DEBUG=true node_modules/.bin/ng-packagr -p ng-package.json`

**Comment by etiennecrb** [comment]
I have the same issue for another lib. It is failing when compiling for rollup:
```
Building Angular Package
[debug] Found primary entry point: wiremind-ngx
[debug] rimraf /XXX/wiremind-ngx/dist
Building entry point 'wiremind-ngx'
Cleaning build directory
[debug] rimraf /XXX/wiremind-ngx/.ng_pkg_build/wiremind-ngx/stage
[debug] rimraf /XXX/wiremind-ngx/.ng_pkg_build/wiremind-ngx/out
[debug] Initializing tsconfig
[debug] Analysing sources for wiremind-ngx
Rendering Stylesheets
Rendering Templates
[debug] Transforming TypeScript sources for wiremind-ngx
Compiling TypeScript sources through ngc
[debug] ngc (v5.2.6)
Bundling to FESM15
[debug] rollup (v0.55.5) /XXX/wiremind-ngx/.ng_pkg_build/wiremind-ngx/out/wiremind-ngx.js to /XXX/wiremind-ngx/.ng_pkg_build/wiremind-ngx/stage/esm2015/wiremind-ngx.js (es)

BUILD ERROR
'createNewHosts' is not exported by node_modules/@angularclass/hmr/dist/index.js
Error: 'createNewHosts' is not exported by node_modules/@angularclass/hmr/dist/index.js
    at error (/XXX/wiremind-ngx/node_modules/rollup/dist/rollup.js:170:15)
    at Module.error (/XXX/wiremind-ngx/node_modules/rollup/dist/rollup.js:17195:9)
    at handleMissingExport (/XXX/wiremind-ngx/node_modules/rollup/dist/rollup.js:17458:12)
    at /XXX/wiremind-ngx/node_modules/rollup/dist/rollup.js:19070:56
    at Array.reduce (native)
    at Graph.handleMissingExport (/XXX/wiremind-ngx/node_modules/rollup/dist/rollup.js:19069:27)
    at Module.trace (/XXX/wiremind-ngx/node_modules/rollup/dist/rollup.js:17292:28)
    at ModuleScope.findVariable (/XXX/wiremind-ngx/node_modules/rollup/dist/rollup.js:14431:28)
    at ReturnValueScope.Scope.findVariable (/XXX/wiremind-ngx/node_modules/rollup/dist/rollup.js:11491:68)
    at Scope.findVariable (/XXX/wiremind-ngx/node_modules/rollup/dist/rollup.js:11491:68)
```
