### ISSUE TITLE
Cannot find module 'tsickle/src/tsickle'

### ISSUE THREAD

**Issue by celestale** [dherges/ng-packagr#605]
## Error when doing ng-packagr -p ng-package.json
```
Error: Cannot find module 'tsickle/src/tsickle'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\louislow\Documents\projects\my-component-library\node_modules\ng-packagr\lib\ngc\create-emit-callback.js:15:17)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

ng-package.json
```
{
    "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
    "lib": {
        "entryFile": "public_api.ts"
    }
}
```
public_api.ts
`export * from './src/app/modules/header/header.module';`

#### Version Information

```
ng-packagr: 2.0.0
angular/cli: 1.6.8
angular/compiler-cli: 4.2.4
typescript: 2.6.2
rxjs: 5.4.2
node: 8.6.0
npm: 5.3.0
``

**Comment by anjmao** [comment]
@celestale Please read https://github.com/dherges/ng-packagr/blob/master/CHANGELOG.md

**Comment by dherges** [comment]
```
$ yarn add --dev ng-packagr@^2.0.0 @angular/compiler@^5.0.0 @angular/compiler-cli@^5.0.0 tsickle
```

**Comment by MrDrProfX** [comment]
For npm: `npm i --save-dev tsickle`
