### ISSUE TITLE
Could not resolve module @angular/core

### ISSUE THREAD

**Issue by zealitude** [dherges/ng-packagr#612]
check the comment below
https://github.com/angular/angular/issues/21925#issuecomment-364306640

In short, start from Angular 5.2, if the npm module contains @ angular/core
an angular project will throw the following error:
> TS2451: Cannot redeclare block-scoped variable 'ngDevMode'. #21925

#### How To Reproduce

https://github.com/zealitude/angular2-schema-form/tree/upgrade-ng5
```
yarn run v1.3.2
$ ng-packagr -p package.json
Building Angular Package
Building entry point 'angular2-schema-form'
Cleaning build directory

BUILD ERROR
Could not resolve module @angular/core
Error: Could not resolve module @angular/core
    at StaticSymbolResolver.getSymbolByModule (/WorkSpace/angular/angular2-schema-form/node_modules/@angular/compiler/bundles/compiler.umd.js:29765:30)
    at StaticReflector.findDeclaration (/WorkSpace/angular/angular2-schema-form/node_modules/@angular/compiler/bundles/compiler.umd.js:31634:63)
    at StaticReflector.initializeConversionMap (/WorkSpace/angular/angular2-schema-form/node_modules/@angular/compiler/bundles/compiler.umd.js:31952:36)
    at new StaticReflector (/WorkSpace/angular/angular2-schema-form/node_modules/@angular/compiler/bundles/compiler.umd.js:31570:14)
    at Object.createAotCompiler (/WorkSpace/angular/angular2-schema-form/node_modules/@angular/compiler/bundles/compiler.umd.js:32956:44)
    at AngularCompilerProgram._createCompiler (/WorkSpace/angular/angular2-schema-form/node_modules/@angular/compiler-cli/src/transformers/program.js:404:37)
    at AngularCompilerProgram.get [as hostAdapter] (/WorkSpace/angular/angular2-schema-form/node_modules/@angular/compiler-cli/src/transformers/program.js:327:22)
    at AngularCompilerProgram._createProgramWithBasicStubs (/WorkSpace/angular/angular2-schema-form/node_modules/@angular/compiler-cli/src/transformers/program.js:435:73)
    at AngularCompilerProgram.initSync (/WorkSpace/angular/angular2-schema-form/node_modules/@angular/compiler-cli/src/transformers/program.js:383:27)
    at AngularCompilerProgram.get [as tsProgram] (/WorkSpace/angular/angular2-schema-form/node_modules/@angular/compiler-cli/src/transformers/program.js:359:22)

error Command failed with exit code 111.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**My question is how to avoid the project bundle with @ angular/core when using ng-packagr.**

#### Version Information

```
ng-packagr: 2.0.0
@angular/*: 5.2.4
typescript: 2.5.3
node: 9.5.0
```

**Comment by zealitude** [comment]
I figured out how to solve the problem:
since the ng-packagr need to depends on @angular/compile, @angular/core 
the build script `ng-packagr -p package.json` should NOT be pointing to the package.json which have ng-packagr  in dev-dependency (due to npm install ng-packagr --save-dev).

the module need it own package.json which don't have ng-packagr in dev-dependency.

**Comment by jberall** [comment]
Sorry for being naive but how do you create a package.json just for ng-packagr?
thanks

**Comment by zealitude** [comment]
for example, from the point of view (I guess) of ng-packagr, you are packing the module into a npm library. 

/Host-Project
- package.json ( install ng-packagr here, `ng-packagr -p src/app/module/package.json` )
- src/app
- src/app/module/public-api.ts
- src/app/module/package.json (your library's package.json )

**Comment by hyphen-wrex** [comment]
removing "module" and "target" fields from tsconfig.json worked for me

**Comment by shirinsheik** [comment]
Hi I am using **ng-pakager** in my application and after that I am building the application with **npm run build** cmd that time its throwing me the same error .

**Comment by snarun** [comment]
Is this resolved? I'm still getting the error.
