### ISSUE TITLE
Arrow lambda not supported in static function

### ISSUE THREAD

**Issue by wulfsberg** [dherges/ng-packagr#696]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
Using an "fat arrow" lambda in a static function results in an error, while an instance method works.

#### How To Reproduce
Using the https://github.com/dherges/ng-packaged as base, change the `foo.component.ts` to
```
@Component({
 selector: 'my-foo',
 template: '<h1>foo</h1>',
 styleUrls: ['./foo.component.scss']
})
export class FooComponent {
 static lambdaDoesntWork() {
   return [].map(o => o);
 }

 lambdaWorks() {
   return [].map(o => o);
 }
}
```
`npm run build:lib` then results in
```
BUILD ERROR
: Error: C:/reference/ng-packaged/my-lib/src/foo/foo.component.ts:3:1: Error encountered in metadata generated for exported symbol 'FooComponent':
C:/reference/ng-packaged/my-lib/src/foo/foo.component.ts:10:19: Metadata collected contains an error that will be reported at runtime: Lambda not supported.
 {"__symbolic":"error","message":"Lambda not supported","line":9,"character":18}
   at C:\reference\ng-packaged\node_modules\@angular\compiler-cli\src\metadata\collector.js:664:27
   at Array.forEach (<anonymous>)
   at validateMetadata (C:\reference\ng-packaged\node_modules\@angular\compiler-cli\src\metadata\collector.js:652:42)
   at MetadataCollector.getMetadata (C:\reference\ng-packaged\node_modules\@angular\compiler-cli\src\metadata\collector.js:507:17)
   at LowerMetadataCache.getMetadataAndRequests (C:\reference\ng-packaged\node_modules\@angular\compiler-cli\src\transformers\lower_expressions.js:264:39)
   at LowerMetadataCache.ensureMetadataAndRequests (C:\reference\ng-packaged\node_modules\@angular\compiler-cli\src\transformers\lower_expressions.js:209:27)
   at LowerMetadataCache.getRequests (C:\reference\ng-packaged\node_modules\@angular\compiler-cli\src\transformers\lower_expressions.js:204:21)
   at C:\reference\ng-packaged\node_modules\@angular\compiler-cli\src\transformers\lower_expressions.js:146:36
   at C:\reference\ng-packaged\node_modules\typescript\lib\typescript.js:2892:86
   at reduceLeft (C:\reference\ng-packaged\node_modules\typescript\lib\typescript.js:2585:30)
```

Removing the static function allows the project to package correctly.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            2.2.0
@angular/compiler:     5.2.9
@angular/compiler-cli: 5.2.9
rollup:                0.55.5
tsickle:               0.27.2
typescript:            2.7.2
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment]
Thats actually an Angular Compiler error.

Lambda functions are not supported in statics, a way to overcome this by using the `@dynamic` flag

example
```ts

// @dynamic
@Component({
 selector: 'my-foo',
 template: '<h1>foo</h1>',
 styleUrls: ['./foo.component.scss']
})
export class FooComponent {
 static lambdaDoesntWork() {
   return [].map(o => o);
 }

 lambdaWorks() {
   return [].map(o => o);
 }
}
```

https://angular.io/guide/aot-compiler

**Comment by wulfsberg** [comment]
Thanks for the explanation.
It blindsided me that code which was working in a "normal" (production) build started throwing *compile* errors; I was bracing for various "cannot find this or that reference" as I was moving modules around. :-)

**Comment by haochi** [comment]
I ran into the same issue, but I was able to resolve it by assigning the result to a variable, then return the variable.

For example, the above example, changing it from:

```ts
 static lambdaDoesntWork() {
   return [].map(o => o);
 }
```

to

```ts
static lambdaDoesntWork() {
   const result = [].map(o => o);
   return result;
 }
```

resolves the issue.

**Comment by alan-agius4** [comment]
This issue looks quite similar to https://github.com/angular/angular/issues/23629

**Comment by serkon** [comment]
l found my way with this solution:

```typescript
export class SomeClass{
  oldMethod(array: any[]) {
    return array.filter((item, pos) => {
      return array.indexOf(item) === pos;
    });
  }

  // method content moved to a variable then referenced to this variable
  newMethod(array: any[]) {
    const filter = (item, pos) => {
      return array.indexOf(item) === pos;
    };
    return array.filter(filter);
  }
}
```

**Comment by KevinGuancheDarias** [comment]
Great @haochi !, just for curiosity, do you know why it works?

**Comment by hitallow** [comment]
These methods don't work for validators. i have this code
`export class CustomValidators {
  static typeIs(
    type:
      | 'object'
      | 'boolean'
      | 'function'
      | 'number'
      | 'string'
      | 'undefined' = 'string'
  ): ValidatorFn {
    return (control: AbstractControl): ReturnType => {
      if (typeof control.value !== type && control.value !== '')
        return { typeIs: true };
      return null;
    };
  }
}`

**Comment by hitallow** [comment]
These methods don't work for custom validators, i have this code.

```
export` class CustomValidators {
  static typeIs(
    type:
      | 'object'
      | 'boolean'
      | 'function'
      | 'number'
      | 'string'
      | 'undefined' = 'string'
  ): ValidatorFn {
    return (control: AbstractControl): ReturnType => {
      if (typeof control.value !== type && control.value !== '')
        return { typeIs: true };
      return null;
    };
  }
}
```
