### ISSUE TITLE
Create a bundle including transpiled protobuf

### ISSUE THREAD

**Issue by Drogglbecher** [dherges/ng-packagr#741]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Hi, this is not really a bug on ng-packagr side but more a request for an approach. I have my angular module which I want to insert into a larger app as node_module. Therefore I split the module app into a `lib` part, which should be bundled and a `e2e_app` part, so I can do the testing for the specific module directly within its repo.

For shipping purposes I take ng-packagr with only the `entryFile` option. This worked fine until I within a service I want bundle I have to use some generated protobuf stuff. This means at least a `proto` file transpiled to js (including typescript definitions) with [ts-protoc-gen](https://www.npmjs.com/package/ts-protoc-gen). The output is located within a  `protobuf` directory within the lib directory.

Now with the import of the generated protobuf in the `permission.service.ts` I got the following error:

```console
BUILD ERROR
Could not resolve '../protobuf/types_pb' from .ng_pkg_build/module-example/out/services/permission.service.js
Error: Could not resolve '../protobuf/types_pb' from .ng_pkg_build/module-example/out/services/permission.service.js
    at error ([...]/module-development/module-example/node_modules/rollup/dist/rollup.js:170:15)
    at [...]/module-development/module-example/node_modules/rollup/dist/rollup.js:19580:25
    at <anonymous>
error An unexpected error occurred: "Command failed.
```

Maybe I'm doing something wrong with the correct inclusion of the protobuf stuff. What is the recommended way to create a bundle with the setup described above?

Thanks & Best
Sebastian

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 2.4.1
@angular/*: 5.2.9
typescript: 2.8.1
rxjs: 5.5.8
node: 9.4.z0
yarn: 1.5.1

google-protobuf: 3.5.0
grpc-web-client: 0.5.0
ts-protoc-gen: 0.5.2
```

**Comment by lohiaad** [comment]
Hi,

I got same error while importing `.json` file.

```
BUILD ERROR
Could not resolve './my-component.locale-strings.json' from modules/shared-module/.ng_pkg_build/shared/out/src/components/my-component/my-component.configuration.js
Error: Could not resolve './my-component.locale-strings.json' from modules/shared-module/.ng_pkg_build/shared/out/src/components/my-component/my-component.configuration.js
    at error (/Users/adityalohia/projects/shared-module/node_modules/rollup/dist/rollup.js:170:15)
    at /Users/adityalohia/projects/shared-module/node_modules/rollup/dist/rollup.js:19580:25
    at <anonymous>
```

**Comment by Drogglbecher** [comment]
> Should the generated sources be written to the dist bundle files?

This would be one approach. When it's possible it may be enough to add the generated javascript and typescript definitions as kind of external module and ship it within the bundle.

**Comment by sclausen** [comment]
I would like to embedd a browserified bundle. I think that would be the same usecase.

**Comment by salvani-aldo** [comment]
hi, any updates on this? i am also facing the same problem on protobuf generated .ts files
