### ISSUE TITLE
Error: Cannot find module '@angular/compiler-cli'

### ISSUE THREAD

**Issue by jtpdev** [dherges/ng-packagr#746]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I Create a project and I'm trying to publich it on npm, but when I try to run:

> npm run packagr

It happens:

module.js:549
    throw err;
    ^

Error: Cannot find module '@angular/compiler-cli'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\ng-packagr\lib\ts\tsconfig.js:3:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jtp-alert@0.1.0 packagr: `npm run clear && ng-packagr -p ng-package.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jtp-alert@0.1.0 packagr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-04-04T16_32_57_920Z-debug.log

**Comment by slavafomin** [comment]
Hello! @jtpdev, how have you managed to fix this?

**Comment by jtpdev** [comment]
Yeah, https://stackoverflow.com/a/43931987 help me!
