### ISSUE TITLE
Build fails with third-party library (ng-formly)

### ISSUE THREAD

**Issue by DDeis** [dherges/ng-packagr#75]
I have a working module and I want to make a library out of it so I can use it in other projects (https://github.com/DDeis/ng-formly-add-ons). After many research I stumbled upon **ng-packagr**. I followed the _Readme_ of https://github.com/dherges/ng-packaged, but when I run `ng-packagr` I uncounter the following error:

```shell
➜ npm run build:lib

> formly-add-ons@0.0.0-alpha.0 build:lib /home/ahmad/Documents/Damien/Projets/ng-formly-add-ons
> DEBUG=true ng-packagr

Building Angular library from /home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/ng-package.json
[debug] rimraf /home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/dist/ng-formly-add-ons
[debug] rimraf /home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/.ng_build
[debug] processAssets /home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/ng-formly-add-ons to /home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/.ng_build/ts
[debug] ngc /home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/.ng_build/ts/tsconfig.lib.json, { basePath: /home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/.ng_build/ts })

BUILD ERROR
Cannot read property 'path' of undefined
TypeError: Cannot read property 'path' of undefined
    at TsickleCompilerHost.getSourceMapKeyForSourceFile (/home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/tsickle/build/src/tsickle_compiler_host.js:120:65)
    at TsickleCompilerHost.closurize (/home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/tsickle/build/src/tsickle_compiler_host.js:220:41)
    at TsickleCompilerHost.getSourceFile (/home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/tsickle/build/src/tsickle_compiler_host.js:96:29)
    at findSourceFile (/home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/typescript/lib/typescript.js:70246:29)
    at processImportedModules (/home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/typescript/lib/typescript.js:70393:25)
    at findSourceFile (/home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/typescript/lib/typescript.js:70274:17)
    at processImportedModules (/home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/typescript/lib/typescript.js:70393:25)
    at findSourceFile (/home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/typescript/lib/typescript.js:70274:17)
    at args (/home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/typescript/lib/typescript.js:70200:85)
    at getSourceFileFromReferenceWorker (/home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/typescript/lib/typescript.js:70173:34)

npm ERR! code ELIFECYCLE
npm ERR! errno 111
npm ERR! formly-add-ons@0.0.0-alpha.0 build:lib: `DEBUG=true ng-packagr`
npm ERR! Exit status 111
npm ERR! 
npm ERR! Failed at the formly-add-ons@0.0.0-alpha.0 build:lib script.
```

It seems I get this error when I'm importing a third-party library (ng-formly) in my [library module](https://github.com/DDeis/ng-formly-add-ons/blob/master/ng-formly-add-ons/src/formly-add-ons.module.ts) or when I'm importing constants.

It may be more of a _support request_ than a _bug report_, I'm pretty new at developping librairies so I don't know if it comes from my code or if it has something to do with AOT. I have been struggling on this all day and found nothing on the web, so any idea on this ? :-)

**Comment by dherges** [comment]
Hi,

If I needed to debug this, I'd try to get more info out of the exception and set a breakpoint / console.log() near the error source at

node_modules/tsickle/build/src/tsickle_compiler_host.js:120:65

Cheers, David

**Comment by DDeis** [comment]
Hi David,

Thank you for your answer, after some debugging it seems that the library I'm using doesn't have a `.d.ts` file at the root.


The TsickleCompilerHost try to get the source file for `/<path>/node_modules/ng-formly/index.ts` but gets `undefined`.

```shell
getSourceFile: /home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/@angular/forms/src/directives/number_value_accessor.d.ts
getSourceFile: /home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/@angular/forms/src/directives/range_value_accessor.d.ts
getSourceFile: /home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/@angular/forms/src/directives/ng_no_validate_directive.d.ts
getSourceFile: /home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/ng-selectize/index.d.ts
getSourceFile: /home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/ng-selectize/ng-selectize.module.d.ts
getSourceFile: /home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/ng-selectize/ng-selectize.component.d.ts
getSourceFile: /home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/.ng_build/ts/src/formly-add-ons-config.ts
getSourceFile: /home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/ng-formly/index.ts
undefined

BUILD ERROR
Cannot read property 'path' of undefined
TypeError: Cannot read property 'path' of undefined
    at TsickleCompilerHost.getSourceMapKeyForSourceFile (/home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/tsickle/build/src/tsickle_compiler_host.js:124:65)
    at TsickleCompilerHost.closurize (/home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/tsickle/build/src/tsickle_compiler_host.js:224:41)
    at TsickleCompilerHost.getSourceFile (/home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/tsickle/build/src/tsickle_compiler_host.js:100:29)
    at findSourceFile (/home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/typescript/lib/typescript.js:70246:29)
    at findSourceFile (/home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/typescript/lib/typescript.js:70246:29)
    at processImportedModules (/home/ahmad/Documents/Damien/Projets/ng-formly-add-ons/node_modules/typescript/lib/typescript.js:70393:25)
   ...
```

It seems that other source files are `.d.ts` expect for the one in .ng_build and the library causing problems. Though an `index.d.ts` file exists for ng-formly but it's in the `lib/src` folder as `typings` tells in the ng-formly `package.json`. Why does the compiler fails to fetch the good typings files for ng-formly?

**Comment by dherges** [comment]
I still don't get it.

In node_modules/ng-formly/package.json:

```json
{
  "typings": "./lib/src/index.d.ts"
}
```

Right?

Does that file in `node_modules/ng-formly/lib/src/index.d.ts` exist? 

What looks strange is this `getSourceFile <...>/node_modules/ng-formly/index.ts`. Usually, it should not resolve to TypeScript sources of a library but rather only the type definitions. It should not try to re-transpile TypeScript sources of a library. It should only "link" against the TypeScript symbols (thus d.t.s) for type validation.

**Comment by DDeis** [comment]
Yes in `node_modules/ng-formly/package.json` (https://github.com/formly-js/ng-formly/blob/master/package.json#L11), typings is set to `lib/src/index.d.ts`.

Yes that what I noticed and don't understand why... Though the autor published a new package (@ng-formly/core) which will be the next version of ng-formly following the Angular Package Format and it works properly with it.

So this issue is maybe more related to the actual version of ng-formly than ng-packagr I think. Unless you want to investigate more about what's causing this error, I have no objection to closing this issue.
