### ISSUE TITLE
[Bug Report] TypeScript linting warnings get treated as errors

### ISSUE THREAD

**Issue by Chan4077** [dherges/ng-packagr#818]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

TypeScript linting warnings are considered as errors for some reason:

```
edricchan@Edrics-Macbook-Pro:~/Desktop/Projects/angular/my-packages/ngx-ytd-api$ npm run packagr

> ngx-ytd-api@1.0.0-alpha.0 packagr /Users/edricchan/Desktop/Projects/angular/my-packages/ngx-ytd-api
> ng-packagr -p ng-package.json

Building Angular Package
Building entry point 'ngx-ytd-api'
Cleaning build directory
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc

BUILD ERROR
src/lib/ytd-api.service.ts(11,2): warning TS0: @private annotations are redundant with TypeScript equivalents
src/lib/ytd-api.service.ts(18,2): warning TS0: the type annotation on @param is redundant with its TypeScript type, remove the {...} part
the type annotation on @param is redundant with its TypeScript type, remove the {...} part
the type annotation on @return is redundant with its TypeScript type, remove the {...} part
src/lib/ytd-api.service.ts(11,2): warning TS0: @private annotations are redundant with TypeScript equivalents

Error: src/lib/ytd-api.service.ts(11,2): warning TS0: @private annotations are redundant with TypeScript equivalents
src/lib/ytd-api.service.ts(18,2): warning TS0: the type annotation on @param is redundant with its TypeScript type, remove the {...} part
the type annotation on @param is redundant with its TypeScript type, remove the {...} part
the type annotation on @return is redundant with its TypeScript type, remove the {...} part
src/lib/ytd-api.service.ts(11,2): warning TS0: @private annotations are redundant with TypeScript equivalents

    at Object.<anonymous> (/Users/edricchan/Desktop/Projects/angular/my-packages/ngx-ytd-api/node_modules/ng-packagr/lib/ngc/compile-source-files.js:69:35)
    at Generator.next (<anonymous>)
    at /Users/edricchan/Desktop/Projects/angular/my-packages/ngx-ytd-api/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/edricchan/Desktop/Projects/angular/my-packages/ngx-ytd-api/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/Users/edricchan/Desktop/Projects/angular/my-packages/ngx-ytd-api/node_modules/ng-packagr/lib/ngc/compile-source-files.js:19:12)
    at Object.<anonymous> (/Users/edricchan/Desktop/Projects/angular/my-packages/ngx-ytd-api/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:37:60)
    at Generator.next (<anonymous>)
    at /Users/edricchan/Desktop/Projects/angular/my-packages/ngx-ytd-api/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)

npm ERR! code ELIFECYCLE
npm ERR! errno 111
npm ERR! ngx-ytd-api@1.0.0-alpha.0 packagr: `ng-packagr -p ng-package.json`
npm ERR! Exit status 111
npm ERR! 
npm ERR! Failed at the ngx-ytd-api@1.0.0-alpha.0 packagr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/edricchan/.npm/_logs/2018-04-28T16_32_24_811Z-debug.log
edricchan@Edrics-Macbook-Pro:~/Desktop/Projects/angular/my-packages/ngx-ytd-api$ 
```
(P.S. Here's the file in question:)

```typescript
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { HttpClient } from '@angular/common/http';

import { NgxYtdApiVideoOpts } from './ytd-api.interfaces';

@Injectable({
	providedIn: 'root'
})
export class NgxYtdApiService {
	/**
	 * The YouTube base API URL
	 * @private
	 */
	private ytdApiBaseUrl = 'https://www.googleapis.com/youtube/v3/';
	constructor(private http: HttpClient) { }

	/**
	 * Searches for videos using the YouTube API
	 * @param {string} query The query to search for
	 * @param {NgxYtdApiVideoOpts} opts Options for YouTube Data API for Videos
	 * @returns {Observable<any>} Results of the search as a stream
	*/
	searchVideos(query: string, opts?: NgxYtdApiVideoOpts): Observable<any> {
		return this.http.get(`${this.ytdApiBaseUrl}search?q=${query}&maxResults=${opts.maxResults ? opts.maxResults : 50}&type=video&part=snippet,id&key=${opts.apiKey}&videoEmbeddable=${opts.videoEmbeddable}`);
	}
}

```

#### How To Reproduce

1. Setup an Angular project.
2. Add a service using `ng g s my-service`.
3. Add a method in the service file with JSDocs.
    ```typescript
    /** 
     * Random JSDoc
     */
    getData(test: string) {
      // blah blah
    }
4. Add a `@param` tag to signify a parameter and add data assignment (aka `{...}`) before the variable:
  ```typescript
  /**
   * Random JSDoc
   * @param {string} test The test string
   */
  getData(test: string) {
    // blah blah
  }
  ```
3. Compile with `ng-packagr`.
    
    It should show that it's a "warning", but in `ng-packagr`, it shows as an error:
    ```
    BUILD ERRORS
    src/app/my-file.service.ts(10,2): warning TS0: the type annotation on @param is redundant with its TypeScript type, remove the {...} part
    the type annotation on @param is redundant with its TypeScript type, remove the {...} part
    ```
#### Expected Behaviour

The warnings should just be warnings and not be considered as errors.

Maybe add a "Build warnings" section?

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
```
Dependencies | Version
---|---
`ng-packagr` | 2.4.2
`@angular/compiler` | 6.0.0-rc.6
`@angular/compiler-cli` | 6.0.0-rc.6
`rollup` | 0.55.5
`tsickle` | 0.27.5
`typescript` | 2.7.2

**Comment by matheusdavidson** [comment]
My solution, in angular 7, was change my ```tsconfig.lib.json``` config, 

from this:
```json
"angularCompilerOptions": {
    "annotateForClosureCompiler": true
    ...
    ...
}
```
to this:
```json
"angularCompilerOptions": {
    "annotateForClosureCompiler": false
    ...
    ...
}
```

**Comment by jeanRandria** [comment]
Change "no-redundant-jsdoc": true to "no-redundant-jsdoc": false,
restart Visual code
