### ISSUE TITLE
Cannot find module "@angular/compiler"

### ISSUE THREAD

**Issue by hggeorgiev** [dherges/ng-packagr#865]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

For some reason, I can no longer build my package. I tried reinstalling `@angular/cli` but to no avail. Bundling works at node version `~8` but the latest version of `@angular/cli` does not support it.
```
ng-packagr -p ng-package.json

internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module '@angular/compiler'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/hgeorgiev/.config/yarn/global/node_modules/@angular/compiler-cli/index.js:20:22
    at /Users/hgeorgiev/.config/yarn/global/node_modules/@angular/compiler-cli/index.js:3:17
    at Object.<anonymous> (/Users/hgeorgiev/.config/yarn/global/node_modules/@angular/compiler-cli/index.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)

```
#### Expected Behaviour

Building a package

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 2.4.4
@angular/*: 6.0.0
typescript: 2.7.2
rxjs: 6.1.0
node: 10.0.0
npm/yarn:   5.6.0/1.2.1
```

**Comment by alan-agius4** [comment]
Is @angular/compiler installed?

**Comment by hggeorgiev** [comment]
It kind of sorted itself out after reinstalling `@angular/cli`. I think it's an issue with the edge versions of the packages I am using.

**Comment by kumaresan-subramani** [comment]
any solution for this?

**Comment by redplane** [comment]
Any solutions ? I'm using `ng-packagr` verison `5.3.0`
