### ISSUE TITLE
Testsuite fails on windows

### ISSUE THREAD

**Issue by pfeigl** [dherges/ng-packagr#890]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Running the test suite on the current master fails in two tests when executed on windows. This is due to windows folders where hardcoded linux paths are expected.

```
 102 passing (90ms)
  2 failing

  1) transformComponentSourceFiles()
       stylesheet: StylesheetTransformer
         should resolve file path of the stylesheet file relative to source file:

      AssertionError: expected { Object (node, sourceFile, ...) } to have property 'styleFilePath' of '/foo-bar/foo.component.css', but got 'C:\\foo-bar\\foo.component.css'
      + expected - actual

      -C:\foo-bar\foo.component.css
      +/foo-bar/foo.component.css

      at Context.<anonymous> (src\lib\ts\ng-component-transformer.spec.ts:132:38)

  2) transformComponentSourceFiles()
       template: TemplateTransformer
         should resolve file path of the template file relative to source file:

      AssertionError: expected { Object (node, sourceFile, ...) } to have property 'templateFilePath' of '/foo-bar/foo.component.html', but got 'C:\\foo-bar\\foo.component.html'
      + expected - actual

      -C:\foo-bar\foo.component.html
      +/foo-bar/foo.component.html

      at Context.<anonymous> (src\lib\ts\ng-component-transformer.spec.ts:170:36)
```

#### How To Reproduce

`yarn test` on a windows machine

#### Expected Behaviour

All tests pass

#### Version Information

`master` branch as of `57f5ed9c2fb8dffa4b7dfc586245b9c0b5480f57`

**Comment by alan-agius4** [comment]
This should be solved when https://github.com/dherges/ng-packagr/pull/872 is merged as this spec was removed.

**Comment by pfeigl** [comment]
Great, and than I'm also glad I did not yet start fixing the problems. Also the change in #872 is very nice

**Comment by alan-agius4** [comment]
This should be solved now

**Comment by dherges** [comment]
We need a windows-based CI!

**Comment by alan-agius4** [comment]
AppVeyor 😀?

**Comment by dherges** [comment]
Would be nice!
