### ISSUE TITLE
Bug: Cannot find module 'less'

### ISSUE THREAD

**Issue by deebloo** [dherges/ng-packagr#91]
**Version:**: 1.0.0-pre.13

**Description:**
If I do not manually install Less ng-packagr complains that it cannot find the module even if I do not want to compile and less files

**To Reproduce:**
npm i --save-dev ng-packagr@1.0.0-pre.13
ng-packagr -p ng-package.json

**Error Message:**
Error: Cannot find module 'less'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/dannyblue/Documents/projects/example-lib/node_modules/ng-packagr/lib/steps/assets.js:12:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

**Comment by deebloo** [comment]
So i tried again and I can't reproduce. maybe a bad install? ill close this and open it again if I find it again

**Comment by dherges** [comment]
for whatever reason, less was added to `devDependencies` but it should be in the `dependencies` for sure.

**Comment by deebloo** [comment]
I wonder why my issue went away. maybe after I installed it manually it got stuck in the package-lock or something

**Comment by dherges** [comment]
I think so! It went unnoticed because Angular CLI installs less, e.g. [here](https://github.com/dherges/ng-packaged/blob/master/yarn.lock#L3215)
