### ISSUE TITLE
Works on Windows flawlessly, breaks on Mac all the time

### ISSUE THREAD

**Issue by ledicjp** [dherges/ng-packagr#929]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I get this on MacOS, when trying to run ng-packagr...
I've tried all the things that I could find about this error, so about 5-6 different causes and solutions from various websites, including a fresh reinstallation of nodejs & npm, but I just can't get this to work on MacOS. On my windows desktop the package can be built without any errors with the same package.json, same tsconfig etc...

```
Could not resolve module @angular/core
Error: Could not resolve module @angular/core
at StaticSymbolResolver.getSymbolByModule (/Users/.../node_modules/@angular/compiler/bundles/compiler.umd.js:19543:30)
at StaticReflector.findDeclaration (/Users/.../node_modules/@angular/compiler/bundles/compiler.umd.js:20900:63)
at StaticReflector.initializeConversionMap (/Users/.../node_modules/@angular/compiler/bundles/compiler.umd.js:21137:51)
at new StaticReflector (/Users/.../node_modules/@angular/compiler/bundles/compiler.umd.js:20868:14)
at Object.createAotCompiler (/Users/.../node_modules/@angular/compiler/bundles/compiler.umd.js:21897:27)
at AngularCompilerProgram._createCompiler (/Users/.../node_modules/@angular/compiler-cli/src/transformers/program.js:584:41)
at AngularCompilerProgram.get [as hostAdapter] (/Users/.../node_modules/@angular/compiler-cli/src/transformers/program.js:465:26)
at AngularCompilerProgram._createProgramWithBasicStubs (/Users/.../node_modules/@angular/compiler-cli/src/transformers/program.js:615:77)
at AngularCompilerProgram.initSync (/Users/.../node_modules/@angular/compiler-cli/src/transformers/program.js:563:31)
at AngularCompilerProgram.get [as structuralDiagnostics] (/Users/.../node_modules/@angular/compiler-cli/src/transformers/program.js:486:26)
```

### As far as I understand,
I don't have to put the @angular/* dependencies under `dependencies` in the package.json. I have some peerDependencies defined as well as devDependencies, but even if I add them to `depenencies` I still get the same error.

#### How To Reproduce

I honestly don't know what causes this.

#### Expected Behaviour

It should work on MacOS with the same config that works on Windows

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 3.0.1
@angular/*: 6.0.4
typescript: 2.7.2
rxjs: 6.1.0
node: 10.x
npm/yarn: 6.1.0
```

### Those are my dependencies in package.json
```
"peerDependencies": {
    "@angular-redux/store": "6.5.7",
    "@angular/animations": "6.0.1",
    "@angular/cdk": "6.0.1",
    "@angular/common": "6.0.1",
    "@angular/core": "6.0.1",
    "@angular/forms": "6.0.1",
    "@angular/http": "6.0.1",
    "@angular/platform-browser": "6.0.1",
    "@angular/platform-browser-dynamic": "6.0.1",
    "@angular/router": "6.0.1",
    "angular2-hotkeys": "2.0.4",
    "bootstrap": "4.1.1",
    "core-js": "2.5.6",
    "css-element-queries": "0.4.0",
    "element-resize-detector": "1.1.12",
    "elkjs": "0.0.1",
    "font-awesome": "4.7.0",
    "jsplumb": "2.6.12",
    "ngx-bootstrap": "2.0.4",
    "ngx-toastr": "^8.5.1",
    "redux": "3.7.2",
    "rxjs": "6.1.0",
    "zone.js": "0.8.26",
    "rxjs-compat": "^6.0.0-rc.0"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^6.0.2",
    "@angular-devkit/build-angular": "0.6.8",
    "@angular-devkit/core": "0.6.8",
    "@angular/compiler": "6.0.4",
    "typescript": "~2.7.2",
    "@angular/cli": "~6.0.3",
    "ng-packagr": "3.0.1",
    "@angular/language-service": "^6.0.2",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslib": "1.9.2",
    "tslint": "~5.9.1"
  }
```

**Comment by alan-agius4** [comment]
`peerDependencies`, don't get installed, you'd need to add these to `devDependencies` as well.

Try to add `@angular/core` in `devDependencies` and do `npm install`. This should fix the problem.

**Comment by ledicjp** [comment]
I've tried adding `@angular/core` as suggested, but I get the identical error as in my initial post. And it really is installed under `devDependencies`. Maybe it has something to do with node being installed incorrectly on MacOS, all my research so far points to this possibility. It's not your fault for sure.
