### ISSUE TITLE
Problem importing multiple private modules into the library main module

### ISSUE THREAD

**Issue by confraria** [dherges/ng-packagr#952]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] Support
```

## Description

My library main module import exports other smaller modules that I would like to keep private for now, like so:

```ts
import { NgModule } from '@angular/core';
import { NpmModuleA } from 'npm-module-A';
import { NpmModuleB } from 'npm-module-b';
import { InnerModuleA } './inner-a';
import { InnerModuleB } './inner-B';

@NgModule({
 imports: [
    NpmModuleA,
    NpmModuleB,
    InnerModuleA,
    InnerModuleB,
  ],
  exports: [
    NpmModuleA,
    NpmModuleB,
    InnerModuleA,
    InnerModuleB,
  ]
})
export class ComponentsModule {}
```

The bundles and the metadata are generated without errors. However when consuming in another project the a webpack error is triggerd on first compilation.

```
ERROR in Cannot read property 'members' of undefined
```
and here is the stack trace:
```
TypeError: Cannot read property 'members' of undefined
    at AotSummaryResolver.resolveSummary (node_modules/@angular/compiler/bundles/compiler.umd.js:21811:39)
    at CompileMetadataResolver._loadSummary (node_modules/@angular/compiler/bundles/compiler.umd.js:10210:49)
    at CompileMetadataResolver._getEntryComponentMetadata (node_modules/@angular/compiler/bundles/compiler.umd.js:10993:31)
    at node_modules/@angular/compiler/bundles/compiler.umd.js:10638:53
    at Array.map (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (node_modules/@angular/compiler/bundles/compiler.umd.js:10638:18)
    at CompileMetadataResolver.getNgModuleSummary (node_modules/@angular/compiler/bundles/compiler.umd.js:10464:35)
    at node_modules/@angular/compiler/bundles/compiler.umd.js:10551:55
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (node_modules/@angular/compiler/bundles/compiler.umd.js:10529:49)
    at visitLazyRoute (node_modules/@angular/compiler/bundles/compiler.umd.js:20578:68)
    at AotCompiler.listLazyRoutes (node_modules/@angular/compiler/bundles/compiler.umd.js:20534:20)
    at AngularCompilerProgram.listLazyRoutes (node_modules/@angular/compiler-cli/src/transformers/program.js:226:34)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (node_modules/@angular/compiler-cli/src/ngtools_api.js:46:40)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:279:66)
    at Promise.resolve.then.then (node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:612:50)
```

Following the stack trace this seems to happen because at a certain point my module metadata is something like what is represented below and the ```undefined``` values are eventually passed to AotSummaryResolver.resolveSummary.

```
{
   ngMetadataName: 'NgModule',
   exports: [
      StaticSymbol { },
      StaticSymbol { },
      undefined,
      undefined,
   ]
    exports: [
      StaticSymbol { },
      StaticSymbol { },
      undefined,
      undefined,
   ]
}
```  

Suprisingly, when using using the dev server and after a file change triggers a recompilation, the error is gone and the app runs fine!
I've also tried to export the the inner modules in the public_api barrel, but with the same results.

Will I have to use a single angular module or am I missing something?

**Comment by alan-agius4** [comment]
I highly doubt this is an ng-packagr issue as it looks like it might be an angular compiler issue.

However, in order to determine the cause. Can you please provide a small reproduction?

Thanks

**Comment by confraria** [comment]
🤦‍♂️  the problem was in an entry component declaration in the main module.
```
{
entryComponent: [ ComponentFromInnerModuleA ]
}
```
As it was already defined in ```InnerModuleA``` ijust removing it from the main module solved it. :)
Thank you for you time :)
